/* La carta de Tinge of Turmeric.
 *
 * Fuente: la página oficial de la carta de Tinge of Turmeric, extraída el 2026-08-20.
 * Moneda: EUR. Los precios llevan punto decimal para que el importador los tome tal cual.
 * Las descripciones son resúmenes cortos escritos para la web; no están copiadas literalmente
 * del original.
 *
 * Este fichero sustituye al menu.md que se mantenía a mano. De aquí salen menu.md, i18n.es.mjs
 * e i18n.de.mjs con `node importar.mjs`. Editar esos tres a mano no sirve de nada: la
 * siguiente pasada del importador los reescribe. Lo que se edita es este fichero.
 *
 * El texto base es INGLÉS: es lo que ve quien pone el idioma en English y lo que indexa
 * Google. Detrás van el español y el alemán, en ese orden, que es el de IDIOMAS_CLIENTE en
 * cliente.mjs.
 *
 * Formato de cada fila de plato:
 *   [ nombre en, nombre es, nombre de,
 *     descripción en, descripción es, descripción de,
 *     precio, número ]
 *
 * Reglas del formato:
 *   - Un plato sin descripción lleva la cadena vacía '', no null.
 *   - El precio va como texto y con punto decimal: '11.95', no 11,95. 'included' es un precio
 *     válido y sale como «Included» en la carta: son las salsas, que no se cobran aparte.
 *   - El número es el que ve el comensal impreso a la izquierda del plato, y NO es correlativo:
 *     la carta original salta del 67 al 69, desdobla el 24 en 24a/24b/24c y deja sin número las
 *     listas de salsas, ingredientes y las pestañas Sin gluten y Vegano. Por eso va escrito aquí
 *     uno a uno en vez de contarlo el importador. Cambiar un número cambia lo que se ve.
 *   - `categoria` es una clave interna: agrupa los platos y nunca se enseña. Lo que ve el
 *     comensal es la pestaña (`pestana`) y el subtítulo (`subtitulo`).
 *   - `nota` es opcional: la frase que vale para TODOS los platos del grupo. Sale bajo el
 *     título de la categoría.
 *
 * Iconos disponibles, y no hay más:
 *   appetizers · soup · vegetarian · meat · salad · flame · leaf · lentils
 *   rice · bread · fries · special · kids · bowl · drop · gf
 *
 * FUERA DE LA CARTA — «South Indian Curries - Ingredients». La carta impresa repetía los
 * catorce ingredientes de los currys: una vez para las salsas clásicas y otra, idénticos en
 * nombre, descripción y precio, para las del sur de la India. Aquí se listan UNA vez, en
 * «Curries - Ingredients», y después se elige salsa de una familia o de la otra. No se ha
 * quitado ningún plato: se ha quitado una copia, igual que ya se hacía antes de la migración.
 */
export const CARTA = [
  {
    pestana: ['Appetizers & Soups', 'Aperitivos y sopas', 'Kleinigkeiten & Suppen'],
    icono: 'soup',
    grupos: [
      {
        categoria: 'Appetizers',
        subtitulo: ['Appetizers', 'Aperitivos', 'Kleinigkeiten'],
        icono: 'appetizers',
        platos: [
          ['Papadum', 'Papadum', 'Papadum',
           'Crisp lentil wafer.',
           'Oblea crujiente de lenteja.',
           'Knuspriger Linsenfladen.',
           '1.00', '01'],
          ['Spicy Papadum', 'Papadum especiado', 'Papadum mit Gewürzen',
           'Crisp lentil wafer seasoned with spices.',
           'Oblea crujiente de lenteja con especias.',
           'Knuspriger Linsenfladen mit Gewürzen.',
           '1.00', '02'],
          ['Pickle Tray', 'Surtido de encurtidos', 'Pickle-Auswahl',
           'Selection of chutneys, pickles and onions.',
           'Selección de chutneys, encurtidos y cebolla.',
           'Auswahl an Chutneys, Pickles und Zwiebeln.',
           '3.00', '03'],
          ['Pick Any Individual Sauce or Pickle', 'Salsa o encurtido a elegir', 'Sauce oder Pickle nach Wahl',
           'Choose mango, mint, onions, spiced onions, tamarind sauce or lime pickle.',
           'A elegir entre mango, menta, cebolla, cebolla especiada, salsa de tamarindo o encurtido de lima.',
           'Zur Wahl: Mango, Minze, Zwiebeln, gewürzte Zwiebeln, Tamarindensauce oder Limetten-Pickle.',
           '1.10', '04'],
          ['Plain Natural Yogurt', 'Yogur natural', 'Naturjoghurt',
           'Plain natural yogurt.',
           'Yogur natural sin azúcar.',
           'Naturjoghurt ohne Zucker.',
           '2.00', '05'],
          ['Mix Raita', 'Raita de verduras', 'Gemüse-Raita',
           'Yogurt with onion and vegetables.',
           'Yogur con cebolla y verduras.',
           'Joghurt mit Zwiebeln und Gemüse.',
           '3.95', '06'],
        ],
      },
      {
        categoria: 'Soups',
        subtitulo: ['Soups', 'Sopas', 'Suppen'],
        icono: 'soup',
        platos: [
          ['Lentil Soup', 'Sopa de lentejas', 'Linsensuppe',
           'Comforting soup made with mixed lentils.',
           'Sopa reconfortante de lentejas variadas.',
           'Wärmende Suppe aus gemischten Linsen.',
           '7.00', '07'],
          ['Tomato Soup', 'Sopa de tomate', 'Tomatensuppe',
           'Creamy tomato soup seasoned with spices.',
           'Crema de tomate con especias.',
           'Cremige Tomatensuppe mit Gewürzen.',
           '6.50', '08'],
          ['Chicken Soup', 'Sopa de pollo', 'Hühnersuppe',
           'Chicken soup with a light, comforting broth.',
           'Sopa de pollo con un caldo ligero y reconfortante.',
           'Hühnersuppe mit leichter, wärmender Brühe.',
           '7.50', '09'],
        ],
      },
    ],
  },
  {
    pestana: ['Starters', 'Entrantes', 'Vorspeisen'],
    icono: 'appetizers',
    grupos: [
      {
        categoria: 'Starters - Vegetarian',
        subtitulo: ['Vegetarian', 'Vegetarianos', 'Vegetarisch'],
        icono: 'vegetarian',
        platos: [
          ['Onion Pakora', 'Pakora de cebolla', 'Zwiebel-Pakora',
           'Crispy onion fritters in chickpea batter.',
           'Buñuelos crujientes de cebolla en rebozado de garbanzo.',
           'Knusprige Zwiebelkrapfen im Kichererbsenteig.',
           '5.50', '10'],
          ['Spinach Pakora', 'Pakora de espinacas', 'Spinat-Pakora',
           'Crispy spinach fritters in chickpea batter.',
           'Buñuelos crujientes de espinaca en rebozado de garbanzo.',
           'Knusprige Spinatkrapfen im Kichererbsenteig.',
           '6.00', '11'],
          ['Raw Plantain Pakora', 'Pakora de plátano macho', 'Kochbananen-Pakora',
           'Plantain fritters in a spiced chickpea batter.',
           'Buñuelos de plátano macho en rebozado de garbanzo especiado.',
           'Kochbananenkrapfen im gewürzten Kichererbsenteig.',
           '6.00', '12'],
          ['Vegetable Samosa', 'Samosa de verduras', 'Gemüse-Samosa',
           'Fried pastry filled with spiced vegetables.',
           'Empanadilla frita rellena de verduras especiadas.',
           'Frittierte Teigtasche mit gewürztem Gemüse.',
           '5.50', '13'],
          ['Katori Chaat', 'Katori Chaat', 'Katori Chaat',
           'Crisp baskets with potato, chickpeas, yogurt, chutneys and sev.',
           'Cestitas crujientes con patata, garbanzos, yogur, chutneys y sev.',
           'Knusprige Körbchen mit Kartoffel, Kichererbsen, Joghurt, Chutneys und Sev.',
           '8.50', '14'],
          ['Aloo Tikki Chaat', 'Aloo Tikki Chaat', 'Aloo Tikki Chaat',
           'Potato patties topped with yogurt, chutneys and sev.',
           'Tortitas de patata con yogur, chutneys y sev.',
           'Kartoffelplätzchen mit Joghurt, Chutneys und Sev.',
           '8.50', '15'],
          ['Paneer 65', 'Paneer 65', 'Paneer 65',
           'Spicy South Indian-style fried paneer with curry leaves.',
           'Paneer frito picante al estilo del sur de la India, con hojas de curry.',
           'Scharf frittierter Paneer nach südindischer Art mit Curryblättern.',
           '8.50', '16'],
          ['Tandoori Malai Broccoli', 'Brócoli Tandoori Malai', 'Tandoori Malai Brokkoli',
           'Tandoori broccoli finished in a creamy garlic-butter sauce.',
           'Brócoli al tandoor terminado en una salsa cremosa de ajo y mantequilla.',
           'Brokkoli aus dem Tandoor in cremiger Knoblauch-Butter-Sauce.',
           '8.50', '17'],
          ['Chutney Bombs', 'Bombas de chutney', 'Chutney-Bällchen',
           'Crisp paneer-and-potato bites with chutney inside.',
           'Bocaditos crujientes de paneer y patata rellenos de chutney.',
           'Knusprige Paneer-Kartoffel-Bällchen mit Chutney-Füllung.',
           '8.00', '18'],
          ['Cauliflower Wings', 'Alitas de coliflor', 'Blumenkohl-Wings',
           'Spiced, crumbed cauliflower florets fried until crisp.',
           'Ramilletes de coliflor especiados y empanados, fritos hasta quedar crujientes.',
           'Gewürzte, panierte Blumenkohlröschen, knusprig frittiert.',
           '8.00', '19'],
          ['Veg Platter', 'Surtido vegetariano', 'Vegetarische Platte',
           'Selection of Onion Pakora, Spinach Pakora, Raw Plantain Pakora, Tandoori Broccoli and Cauliflower Wings.',
           'Selección de Onion Pakora, Spinach Pakora, Raw Plantain Pakora, Tandoori Broccoli y Cauliflower Wings.',
           'Auswahl an Onion Pakora, Spinach Pakora, Raw Plantain Pakora, Tandoori Broccoli und Cauliflower Wings.',
           '15.95', '20'],
        ],
      },
      {
        categoria: 'Starters - Meat & Seafood',
        subtitulo: ['Meat & Seafood', 'Carne y marisco', 'Fleisch & Meeresfrüchte'],
        icono: 'meat',
        platos: [
          ['Meat Samosa', 'Samosa de carne', 'Fleisch-Samosa',
           'Fried pastry filled with seasoned meat and peas.',
           'Empanadilla frita rellena de carne especiada y guisantes.',
           'Frittierte Teigtasche mit gewürztem Fleisch und Erbsen.',
           '6.50', '21'],
          ['Chicken Pakora', 'Pakora de pollo', 'Hähnchen-Pakora',
           'Marinated chicken pieces fried in a spiced coating.',
           'Trozos de pollo marinados y fritos en rebozado especiado.',
           'Mariniertes Hähnchen in gewürzter Panade frittiert.',
           '6.00', '22'],
          ['How 65 - Chicken or Fish', '65 picante — pollo o pescado', 'Scharfes 65 — Hähnchen oder Fisch',
           'Fiery South Indian-style 65 preparation with curry leaves.',
           'Preparación «65» del sur de la India, muy picante, con hojas de curry.',
           'Feurige Zubereitung „65" nach südindischer Art mit Curryblättern.',
           '9.95', '23'],
          ['Top Up Puri - Chicken', 'Puri con pollo', 'Puri mit Hähnchen',
           'Spiced chicken served over fried puri.',
           'Pollo especiado servido sobre puri frito.',
           'Gewürztes Hähnchen auf frittiertem Puri.',
           '7.50', '24a'],
          ['Top Up Puri - Chicken Chaat', 'Puri con chaat de pollo', 'Puri mit Hähnchen-Chaat',
           'Chicken chaat served over fried puri.',
           'Chaat de pollo servido sobre puri frito.',
           'Hähnchen-Chaat auf frittiertem Puri.',
           '8.00', '24b'],
          ['Top Up Puri - Prawns', 'Puri con gambas', 'Puri mit Garnelen',
           'Spiced prawns served over fried puri.',
           'Gambas especiadas servidas sobre puri frito.',
           'Gewürzte Garnelen auf frittiertem Puri.',
           '8.50', '24c'],
          ['Fish Pakora', 'Pakora de pescado', 'Fisch-Pakora',
           'Boneless fish pieces marinated and fried.',
           'Tacos de pescado sin espinas, marinados y fritos.',
           'Marinierte Fischstücke ohne Gräten, frittiert.',
           '8.50', '25'],
          ['Chicken Tikka', 'Pollo Tikka', 'Hähnchen Tikka',
           'Yogurt-and-spice marinated boneless chicken.',
           'Pollo deshuesado marinado en yogur y especias.',
           'In Joghurt und Gewürzen mariniertes Hähnchen ohne Knochen.',
           '8.00', '26'],
          ['Cheese Chicken Tikka', 'Pollo Tikka con queso', 'Hähnchen Tikka mit Käse',
           'Chicken tikka enriched with cheese.',
           'Pollo Tikka enriquecido con queso.',
           'Hähnchen Tikka mit Käse verfeinert.',
           '9.00', '27'],
          ['Mint Tikka', 'Tikka a la menta', 'Tikka mit Minze',
           'Chicken tikka marinated with mint, herbs and yogurt.',
           'Pollo Tikka marinado con menta, hierbas y yogur.',
           'Hähnchen Tikka mariniert mit Minze, Kräutern und Joghurt.',
           '8.00', '28'],
          ['Malai Tikka', 'Malai Tikka', 'Malai Tikka',
           'Creamy chicken tikka with cheese and yogurt.',
           'Pollo Tikka cremoso con queso y yogur.',
           'Cremiges Hähnchen Tikka mit Käse und Joghurt.',
           '8.00', '29'],
          ['Seekh Kebab', 'Seekh Kebab', 'Seekh Kebab',
           'Seasoned minced meat grilled on skewers.',
           'Carne picada especiada, asada en brocheta.',
           'Gewürztes Hackfleisch am Spieß gegrillt.',
           '9.00', '30'],
          ['Garlic Prawns', 'Gambas al ajillo', 'Knoblauchgarnelen',
           'Prawns cooked with garlic and sauce.',
           'Gambas salteadas con ajo y su salsa.',
           'Garnelen mit Knoblauch und Sauce gebraten.',
           '8.95', '31'],
          ['Tikka Platter', 'Surtido de Tikka', 'Tikka-Platte',
           'Selection of Chicken Tikka, Cheese Chicken Tikka, Pudina Tikka and Malai Tikka.',
           'Selección de Chicken Tikka, Cheese Chicken Tikka, Pudina Tikka y Malai Tikka.',
           'Auswahl an Chicken Tikka, Cheese Chicken Tikka, Pudina Tikka und Malai Tikka.',
           '17.95', '32'],
          ['Meat Kebab Platter', 'Surtido de kebabs de carne', 'Fleisch-Kebab-Platte',
           'Selection of Lamb Tikka, Seekh Kebab and Lamb Chops.',
           'Selección de Lamb Tikka, Seekh Kebab y Lamb Chops.',
           'Auswahl an Lamb Tikka, Seekh Kebab und Lamb Chops.',
           '19.95', '33'],
        ],
      },
    ],
  },
  {
    pestana: ['Salads', 'Ensaladas', 'Salate'],
    icono: 'salad',
    grupos: [
      {
        categoria: 'Salads',
        subtitulo: null,
        platos: [
          ['Garden Salad', 'Ensalada de la huerta', 'Gartensalat',
           'Mixed greens with onion, carrot, tomato and cucumber.',
           'Brotes verdes con cebolla, zanahoria, tomate y pepino.',
           'Blattsalate mit Zwiebel, Karotte, Tomate und Gurke.',
           '6.00', '34'],
          ['Sprouts', 'Ensalada de brotes', 'Sprossensalat',
           'Protein-rich sprouted legumes with greens and onion.',
           'Legumbres germinadas, ricas en proteína, con brotes verdes y cebolla.',
           'Proteinreiche Keimlinge mit Blattsalat und Zwiebel.',
           '11.95', '35'],
          ['Turmeric Quinoa & Chickpea Salad', 'Ensalada de quinoa con cúrcuma y garbanzos', 'Kurkuma-Quinoa-Salat mit Kichererbsen',
           'Turmeric quinoa with chickpeas, fresh vegetables and herbs.',
           'Quinoa a la cúrcuma con garbanzos, verduras frescas y hierbas.',
           'Kurkuma-Quinoa mit Kichererbsen, frischem Gemüse und Kräutern.',
           '12.95', '36'],
          ['Chicken Tikka', 'Pollo Tikka', 'Hähnchen Tikka',
           'Chicken tikka with greens and mixed vegetables.',
           'Pollo Tikka con brotes verdes y verduras variadas.',
           'Hähnchen Tikka mit Blattsalat und gemischtem Gemüse.',
           '14.95', '37'],
          ['Tandoori Prawns', 'Gambas Tandoori', 'Tandoori-Garnelen',
           'Tandoori prawns with greens and mixed vegetables.',
           'Gambas al tandoor con brotes verdes y verduras variadas.',
           'Tandoori-Garnelen mit Blattsalat und gemischtem Gemüse.',
           '15.95', '38'],
          ['Tandoori Paneer', 'Paneer Tandoori', 'Tandoori-Paneer',
           'Tandoori paneer with greens and vegetables; tofu available.',
           'Paneer al tandoor con brotes verdes y verduras; disponible con tofu.',
           'Tandoori-Paneer mit Blattsalat und Gemüse; auch mit Tofu.',
           '14.95', '39'],
          ['Crunchy Vegan Meat', 'Carne vegana crujiente', 'Knuspriges veganes Fleisch',
           'Soy-based vegan protein with greens and vegetables.',
           'Proteína vegana de soja con brotes verdes y verduras.',
           'Veganes Sojaprotein mit Blattsalat und Gemüse.',
           '15.95', '40'],
          ['Tandoori Jackfruit', 'Yaca Tandoori', 'Tandoori-Jackfrucht',
           'Tandoori-marinated jackfruit with greens and vegetables.',
           'Yaca marinada al tandoor con brotes verdes y verduras.',
           'Tandoori-marinierte Jackfrucht mit Blattsalat und Gemüse.',
           '15.95', '41'],
        ],
      },
    ],
  },
  {
    pestana: ['Sizzlers', 'A la plancha', 'Vom heißen Eisen'],
    icono: 'flame',
    grupos: [
      {
        categoria: 'Sizzlers',
        subtitulo: null,
        platos: [
          ['Chicken Tikka', 'Pollo Tikka', 'Hähnchen Tikka',
           'Marinated boneless chicken served sizzling.',
           'Pollo deshuesado marinado, servido en plancha caliente.',
           'Mariniertes Hähnchen ohne Knochen, heiß serviert.',
           '14.95', '42'],
          ['Chicken Shashlik', 'Shashlik de pollo', 'Hähnchen-Shashlik',
           'Chicken, onion and peppers tossed in the house seasoning.',
           'Pollo, cebolla y pimiento salteados con el adobo de la casa.',
           'Hähnchen, Zwiebel und Paprika in der Hausmarinade gebraten.',
           '15.95', '43'],
          ['Tandoori Chicken (with bone)', 'Pollo Tandoori (con hueso)', 'Tandoori-Hähnchen (mit Knochen)',
           'Tandoori-marinated chicken leg quarters.',
           'Cuartos traseros de pollo marinados al tandoor.',
           'Tandoori-marinierte Hähnchenkeulen.',
           '14.95', '44'],
          ['Seekh Kebab', 'Seekh Kebab', 'Seekh Kebab',
           'Minced meat kebabs cooked in the tandoor.',
           'Brochetas de carne picada hechas en el tandoor.',
           'Hackfleischspieße aus dem Tandoor.',
           '16.95', '45'],
          ['Lamb Tikka', 'Cordero Tikka', 'Lamm Tikka',
           'Marinated lamb cubes cooked in the tandoor.',
           'Tacos de cordero marinados y hechos en el tandoor.',
           'Marinierte Lammwürfel aus dem Tandoor.',
           '16.95', '46'],
          ['Lamb Shashlik', 'Shashlik de cordero', 'Lamm-Shashlik',
           'Lamb, onion and peppers tossed in the house seasoning.',
           'Cordero, cebolla y pimiento salteados con el adobo de la casa.',
           'Lamm, Zwiebel und Paprika in der Hausmarinade gebraten.',
           '18.95', '47'],
          ['Fish Shashlik', 'Shashlik de pescado', 'Fisch-Shashlik',
           'Fish, onion and peppers tossed in the house seasoning.',
           'Pescado, cebolla y pimiento salteados con el adobo de la casa.',
           'Fisch, Zwiebel und Paprika in der Hausmarinade gebraten.',
           '19.95', '48'],
          ['King Prawn (with shell)', 'Langostinos (con cáscara)', 'Riesengarnelen (mit Schale)',
           'Large shell-on prawns marinated and cooked tandoori-style.',
           'Langostinos con cáscara, marinados y hechos al tandoor.',
           'Große Garnelen mit Schale, mariniert und im Tandoor gegart.',
           '17.95', '49'],
          ['Tandoori Mix Grill', 'Parrillada Tandoori', 'Tandoori-Grillplatte',
           'Selection of Chicken Tikka, Lamb Tikka, Tandoori Chicken, Seekh Kebab and King Prawns.',
           'Selección de Chicken Tikka, Lamb Tikka, Tandoori Chicken, Seekh Kebab y King Prawns.',
           'Auswahl an Chicken Tikka, Lamb Tikka, Tandoori Chicken, Seekh Kebab und King Prawns.',
           '21.95', '50'],
          ['Paneer Shashlik', 'Shashlik de paneer', 'Paneer-Shashlik',
           'Paneer, onion and peppers in the house seasoning.',
           'Paneer, cebolla y pimiento con el adobo de la casa.',
           'Paneer, Zwiebel und Paprika in der Hausmarinade.',
           '15.95', '51'],
          ['Soy Shashlik', 'Shashlik de soja', 'Soja-Shashlik',
           'Marinated soy, onion and peppers served sizzling.',
           'Soja marinada con cebolla y pimiento, en plancha caliente.',
           'Marinierte Soja mit Zwiebel und Paprika, heiß serviert.',
           '16.95', '52'],
          ['Tandoori Malai Soya', 'Soja Tandoori Malai', 'Tandoori Malai Soja',
           'Tandoori soy in a creamy garlic-butter sauce.',
           'Soja al tandoor en salsa cremosa de ajo y mantequilla.',
           'Soja aus dem Tandoor in cremiger Knoblauch-Butter-Sauce.',
           '16.95', '53'],
          ['Kathal Shashlik', 'Shashlik de Kathal', 'Kathal-Shashlik',
           'Tandoori jackfruit with onion and peppers.',
           'Yaca al tandoor con cebolla y pimiento.',
           'Tandoori-Jackfrucht mit Zwiebel und Paprika.',
           '16.95', '54'],
          ['Extra Sauce', 'Salsa extra', 'Extra Sauce',
           'Choose Tikka Masala, Butter Masala, Korma, Curry or Madras.',
           'A elegir entre Tikka Masala, Butter Masala, Korma, Curry o Madras.',
           'Zur Wahl: Tikka Masala, Butter Masala, Korma, Curry oder Madras.',
           '5.00', ''],
        ],
      },
    ],
  },
  {
    pestana: ['Curries', 'Currys', 'Currys'],
    icono: 'bowl',
    grupos: [
      {
        categoria: 'Curries - Ingredients',
        subtitulo: ['Choose Your Ingredient', 'Elige el ingrediente', 'Zutat wählen'],
        icono: 'bowl',
        nota: ['Spice levels: Mild, Touch, Medium, Madras, Vindaloo, Phall. Select one sauce from the next section.',
               'Niveles de picante: suave, ligero, medio, Madras, Vindaloo y Phall. Elige después una salsa de la lista siguiente.',
               'Schärfegrade: mild, leicht, mittel, Madras, Vindaloo und Phall. Wählen Sie anschließend eine Sauce aus der folgenden Liste.'],
        platos: [
          ['Chicken', 'Pollo', 'Hähnchen',
           'Choose a spice level and curry sauce.',
           'Elige el nivel de picante y la salsa.',
           'Schärfegrad und Currysauce wählen.',
           '12.95', '55'],
          ['Lamb', 'Cordero', 'Lamm',
           'Choose a spice level and curry sauce.',
           'Elige el nivel de picante y la salsa.',
           'Schärfegrad und Currysauce wählen.',
           '14.95', '56'],
          ['Lamb Tikka', 'Cordero Tikka', 'Lamm Tikka',
           'Choose a spice level and curry sauce.',
           'Elige el nivel de picante y la salsa.',
           'Schärfegrad und Currysauce wählen.',
           '15.95', '57'],
          ['Fish', 'Pescado', 'Fisch',
           'Choose a spice level and curry sauce.',
           'Elige el nivel de picante y la salsa.',
           'Schärfegrad und Currysauce wählen.',
           '13.95', '58'],
          ['Prawns', 'Gambas', 'Garnelen',
           'Choose a spice level and curry sauce.',
           'Elige el nivel de picante y la salsa.',
           'Schärfegrad und Currysauce wählen.',
           '14.95', '59'],
          ['King Prawns', 'Langostinos', 'Riesengarnelen',
           'Choose a spice level and curry sauce.',
           'Elige el nivel de picante y la salsa.',
           'Schärfegrad und Currysauce wählen.',
           '16.95', '60'],
          ['Mixed Special (Chicken, Lamb & Prawns)', 'Especial mixto (pollo, cordero y gambas)', 'Gemischt Spezial (Hähnchen, Lamm und Garnelen)',
           'Choose a spice level and curry sauce.',
           'Elige el nivel de picante y la salsa.',
           'Schärfegrad und Currysauce wählen.',
           '18.95', '61'],
          ['Mixed Vegetables', 'Verduras variadas', 'Gemischtes Gemüse',
           'Choose a spice level and curry sauce.',
           'Elige el nivel de picante y la salsa.',
           'Schärfegrad und Currysauce wählen.',
           '11.95', '62'],
          ['Mushrooms', 'Champiñones', 'Champignons',
           'Choose a spice level and curry sauce.',
           'Elige el nivel de picante y la salsa.',
           'Schärfegrad und Currysauce wählen.',
           '11.95', '63'],
          ['Paneer (Indian Cottage Cheese)', 'Paneer (queso fresco indio)', 'Paneer (indischer Frischkäse)',
           'Choose a spice level and curry sauce.',
           'Elige el nivel de picante y la salsa.',
           'Schärfegrad und Currysauce wählen.',
           '13.95', '64'],
          ['Tofu (Prepared from Soymilk)', 'Tofu (elaborado con leche de soja)', 'Tofu (aus Sojamilch)',
           'Choose a spice level and curry sauce.',
           'Elige el nivel de picante y la salsa.',
           'Schärfegrad und Currysauce wählen.',
           '14.95', '65'],
          ['Kathal (Raw Jackfruit)', 'Kathal (yaca verde)', 'Kathal (grüne Jackfrucht)',
           'Choose a spice level and curry sauce.',
           'Elige el nivel de picante y la salsa.',
           'Schärfegrad und Currysauce wählen.',
           '14.95', '66'],
          ['Soy (Processed Soy Bean)', 'Soja (texturizada)', 'Soja (texturiert)',
           'Choose a spice level and curry sauce.',
           'Elige el nivel de picante y la salsa.',
           'Schärfegrad und Currysauce wählen.',
           '14.95', '67'],
          ['Vegan Meat (Soy Based)', 'Carne vegana (a base de soja)', 'Veganes Fleisch (auf Sojabasis)',
           'Choose a spice level and curry sauce.',
           'Elige el nivel de picante y la salsa.',
           'Schärfegrad und Currysauce wählen.',
           '15.95', '69'],
        ],
      },
      {
        categoria: 'Curries - Sauces',
        subtitulo: ['Classic sauces', 'Salsas clásicas', 'Klassische Saucen'],
        icono: 'drop',
        platos: [
          ['Butter Masala', 'Butter Masala', 'Butter Masala',
           'Creamy, buttery and gently sweet sauce.',
           'Salsa cremosa y mantecosa, ligeramente dulce.',
           'Cremige, buttrige und leicht süße Sauce.',
           'included', ''],
          ['Balti', 'Balti', 'Balti',
           'Onion-and-pepper curry traditionally served in a balti bowl.',
           'Curry de cebolla y pimiento, servido tradicionalmente en cazuela balti.',
           'Curry mit Zwiebel und Paprika, traditionell in der Balti-Schale serviert.',
           'included', ''],
          ['Curry', 'Curry', 'Curry',
           'Smooth turmeric-forward house curry.',
           'Curry suave de la casa, con la cúrcuma por delante.',
           'Mildes Hauscurry mit deutlicher Kurkumanote.',
           'included', ''],
          ['Tikka Masala', 'Tikka Masala', 'Tikka Masala',
           'Creamy tomato-based sauce with nuts and mild sweetness.',
           'Salsa cremosa de tomate con frutos secos y un punto dulce.',
           'Cremige Tomatensauce mit Nüssen und milder Süße.',
           'included', ''],
          ['Jalfrezi', 'Jalfrezi', 'Jalfrezi',
           'Stir-fried onion and peppers with a spicy finish.',
           'Cebolla y pimiento salteados con un final picante.',
           'Zwiebel und Paprika gebraten, mit scharfem Abgang.',
           'included', ''],
          ['Dhansak', 'Dhansak', 'Dhansak',
           'Lentil-based curry balancing sweet, sour and spice.',
           'Curry de lentejas que equilibra dulce, ácido y picante.',
           'Linsencurry im Gleichgewicht aus süß, sauer und scharf.',
           'included', ''],
          ['Korma', 'Korma', 'Korma',
           'Mild creamy curry with coconut, nuts and spices.',
           'Curry suave y cremoso con coco, frutos secos y especias.',
           'Mildes, cremiges Curry mit Kokos, Nüssen und Gewürzen.',
           'included', ''],
          ['Bhuna', 'Bhuna', 'Bhuna',
           'Reduced onion-and-spice sauce with caramelised depth.',
           'Salsa reducida de cebolla y especias, con fondo caramelizado.',
           'Eingekochte Zwiebel-Gewürz-Sauce mit karamelliger Tiefe.',
           'included', ''],
          ['Saag', 'Saag', 'Saag',
           'Slow-cooked greens and spices.',
           'Verdura de hoja cocinada a fuego lento con especias.',
           'Blattgemüse mit Gewürzen, langsam geschmort.',
           'included', ''],
          ['Kashmiri', 'Kashmiri', 'Kashmiri',
           'Creamy coconut-and-nut curry with aromatic spices.',
           'Curry cremoso de coco y frutos secos con especias aromáticas.',
           'Cremiges Kokos-Nuss-Curry mit aromatischen Gewürzen.',
           'included', ''],
          ['Dopiaza', 'Dopiaza', 'Dopiaza',
           'Onion-rich curry using onions at two stages.',
           'Curry muy cebollero: la cebolla entra en dos tiempos.',
           'Zwiebelreiches Curry — die Zwiebel kommt in zwei Stufen dazu.',
           'included', ''],
          ['Kashmiri Rogan Josh', 'Kashmiri Rogan Josh', 'Kashmiri Rogan Josh',
           'Slow-cooked onion, fennel and Kashmiri chilli curry.',
           'Curry a fuego lento de cebolla, hinojo y chile de Cachemira.',
           'Langsam geschmortes Curry mit Zwiebel, Fenchel und Kaschmir-Chili.',
           'included', ''],
        ],
      },
      {
        categoria: 'South Indian Curries - Sauces',
        subtitulo: ['South Indian sauces', 'Salsas del sur de la India', 'Südindische Saucen'],
        icono: 'drop',
        platos: [
          ['Kadai', 'Kadai', 'Kadai',
           'Tomato, onion and pepper curry with aromatic spices.',
           'Curry de tomate, cebolla y pimiento con especias aromáticas.',
           'Curry aus Tomate, Zwiebel und Paprika mit aromatischen Gewürzen.',
           'included', ''],
          ['Madras', 'Madras', 'Madras',
           'Tangy tomato-and-onion curry with a chilli-forward profile.',
           'Curry ácido de tomate y cebolla, con el picante por delante.',
           'Säuerliches Tomaten-Zwiebel-Curry mit deutlicher Schärfe.',
           'included', ''],
          ['Garlic Chilli', 'Ajo y guindilla', 'Knoblauch und Chili',
           'House-style garlic and chilli curry with peppers.',
           'Curry de ajo y guindilla de la casa, con pimiento.',
           'Knoblauch-Chili-Curry nach Art des Hauses, mit Paprika.',
           'included', ''],
          ['Chettinad', 'Chettinad', 'Chettinad',
           'Peppery South Indian curry with coconut and aromatic spices.',
           'Curry del sur de la India, con mucha pimienta, coco y especias aromáticas.',
           'Pfeffriges südindisches Curry mit Kokos und aromatischen Gewürzen.',
           'included', ''],
          ['Hyderabadi Handi', 'Hyderabadi Handi', 'Hyderabadi Handi',
           'Slow-cooked creamy yogurt curry with nuts, herbs and spices.',
           'Curry cremoso de yogur a fuego lento, con frutos secos, hierbas y especias.',
           'Cremiges Joghurtcurry, langsam geschmort, mit Nüssen, Kräutern und Gewürzen.',
           'included', ''],
          ['Malabar', 'Malabar', 'Malabar',
           'Milder curry with coconut, yogurt, tamarind and curry leaves.',
           'Curry más suave con coco, yogur, tamarindo y hojas de curry.',
           'Milderes Curry mit Kokos, Joghurt, Tamarinde und Curryblättern.',
           'included', ''],
          ['Goan Vindaloo', 'Vindaloo de Goa', 'Vindaloo aus Goa',
           'Spicy garlic-and-vinegar curry with Portuguese influence.',
           'Curry picante de ajo y vinagre, de raíz portuguesa.',
           'Scharfes Knoblauch-Essig-Curry portugiesischen Ursprungs.',
           'included', ''],
        ],
      },
    ],
  },
  {
    pestana: ['Specialities', 'Especialidades', 'Spezialitäten'],
    icono: 'special',
    grupos: [
      {
        categoria: 'House Specialities',
        subtitulo: null,
        platos: [
          ['Mango Chicken', 'Pollo al mango', 'Hähnchen in Mangosauce',
           'Chicken in a creamy, lightly spiced mango sauce.',
           'Pollo en salsa cremosa de mango, ligeramente especiada.',
           'Hähnchen in cremiger, leicht gewürzter Mangosauce.',
           '15.95', '70'],
          ['Butter Chicken', 'Butter Chicken', 'Butter Chicken',
           'Chicken tikka simmered in a creamy, mildly sweet sauce.',
           'Pollo Tikka cocinado en una salsa cremosa y algo dulce.',
           'Hähnchen Tikka in cremiger, leicht süßer Sauce geschmort.',
           '15.95', '71'],
          ['Kheema Peas', 'Kheema con guisantes', 'Kheema mit Erbsen',
           'Minced meat cooked with peas, tomato, onion and spices.',
           'Carne picada guisada con guisantes, tomate, cebolla y especias.',
           'Hackfleisch mit Erbsen, Tomate, Zwiebel und Gewürzen geschmort.',
           '16.95', '72'],
          ['Bhindi Gosht (Lamb)', 'Bhindi Gosht (cordero)', 'Bhindi Gosht (Lamm)',
           'Lamb and okra in a spiced onion-tomato gravy.',
           'Cordero y okra en salsa especiada de cebolla y tomate.',
           'Lamm und Okra in gewürzter Zwiebel-Tomaten-Sauce.',
           '16.95', '73'],
        ],
      },
    ],
  },
  {
    pestana: ['Vegetables & Lentils', 'Verduras y lentejas', 'Gemüse & Linsen'],
    icono: 'leaf',
    grupos: [
      {
        categoria: 'Vegetable Dishes',
        subtitulo: ['Vegetable Dishes', 'Platos de verdura', 'Gemüsegerichte'],
        icono: 'leaf',
        platos: [
          ['Bombay Aloo', 'Bombay Aloo', 'Bombay Aloo',
           'Potatoes cooked with onion, tomato and spices.',
           'Patata guisada con cebolla, tomate y especias.',
           'Kartoffeln mit Zwiebel, Tomate und Gewürzen geschmort.',
           '10.95', '74'],
          ['Aloo Gobhi', 'Aloo Gobhi', 'Aloo Gobhi',
           'Potato and cauliflower with ground spices.',
           'Patata y coliflor con especias molidas.',
           'Kartoffel und Blumenkohl mit gemahlenen Gewürzen.',
           '10.95', '75'],
          ['Saag Aloo', 'Saag Aloo', 'Saag Aloo',
           'Potatoes cooked with spinach and aromatic spices.',
           'Patata guisada con espinacas y especias aromáticas.',
           'Kartoffeln mit Spinat und aromatischen Gewürzen geschmort.',
           '10.95', '76'],
          ['Chana Masala', 'Chana Masala', 'Chana Masala',
           'Chickpeas cooked with onion, tomato and spices.',
           'Garbanzos guisados con cebolla, tomate y especias.',
           'Kichererbsen mit Zwiebel, Tomate und Gewürzen geschmort.',
           '11.95', '77'],
          ['Aubergine Bharta', 'Bharta de berenjena', 'Auberginen-Bharta',
           'Tandoor-roasted aubergine in a spiced onion-tomato base.',
           'Berenjena asada al tandoor sobre base especiada de cebolla y tomate.',
           'Im Tandoor geröstete Aubergine auf gewürzter Zwiebel-Tomaten-Basis.',
           '12.95', '78'],
          ['Bhindi Masala', 'Bhindi Masala', 'Bhindi Masala',
           'Okra cooked with chopped onion, tomato and spices.',
           'Okra salteada con cebolla picada, tomate y especias.',
           'Okra mit gehackter Zwiebel, Tomate und Gewürzen gebraten.',
           '12.95', '79'],
          ['Malai Kofta', 'Malai Kofta', 'Malai Kofta',
           'Potato-and-paneer dumplings in a creamy sauce.',
           'Albóndigas de patata y paneer en salsa cremosa.',
           'Kartoffel-Paneer-Bällchen in cremiger Sauce.',
           '14.95', '80'],
          ['Mutter Paneer', 'Mutter Paneer', 'Mutter Paneer',
           'Paneer and green peas in a spiced onion-tomato sauce; tofu available.',
           'Paneer y guisantes en salsa especiada de cebolla y tomate; disponible con tofu.',
           'Paneer und Erbsen in gewürzter Zwiebel-Tomaten-Sauce; auch mit Tofu.',
           '14.95', '81'],
          ['Palak Paneer', 'Palak Paneer', 'Palak Paneer',
           'Paneer in spinach purée and spices; tofu available.',
           'Paneer en puré de espinacas con especias; disponible con tofu.',
           'Paneer in Spinatpüree mit Gewürzen; auch mit Tofu.',
           '14.95', '82'],
          ['Navratan Korma', 'Navratan Korma', 'Navratan Korma',
           'Mixed vegetables, fruit and nuts in a creamy korma sauce; tofu available.',
           'Verduras, fruta y frutos secos en salsa Korma cremosa; disponible con tofu.',
           'Gemüse, Obst und Nüsse in cremiger Korma-Sauce; auch mit Tofu.',
           '14.95', '83'],
        ],
      },
      {
        categoria: 'Indian Lentil Dishes',
        subtitulo: ['Indian Lentil Dishes', 'Lentejas indias', 'Indische Linsengerichte'],
        icono: 'lentils',
        platos: [
          ['Yellow Dal Tadka', 'Dal Tadka amarillo', 'Gelbes Dal Tadka',
           'Yellow lentils finished with a fragrant tadka.',
           'Lentejas amarillas terminadas con un tadka aromático.',
           'Gelbe Linsen, vollendet mit aromatischem Tadka.',
           '10.95', '84'],
          ['Dal Makhani', 'Dal Makhani', 'Dal Makhani',
           'Black lentils cooked with tomato, cream, butter and spices.',
           'Lentejas negras guisadas con tomate, nata, mantequilla y especias.',
           'Schwarze Linsen mit Tomate, Sahne, Butter und Gewürzen.',
           '12.95', '85'],
          ['Palak Dal (Spinach)', 'Palak Dal (espinacas)', 'Palak Dal (Spinat)',
           'Lentils cooked with spinach and a seasoned tadka.',
           'Lentejas guisadas con espinacas y un tadka especiado.',
           'Linsen mit Spinat und gewürztem Tadka.',
           '12.95', '86'],
        ],
      },
    ],
  },
  {
    pestana: ['Biryani', 'Biryani', 'Biryani'],
    icono: 'rice',
    grupos: [
      {
        categoria: 'Classic Biryani',
        subtitulo: ['Classic Biryani', 'Biryani clásico', 'Klassisches Biryani'],
        icono: 'rice',
        nota: ['Spice levels: Mild, Touch, Medium, Madras, Vindaloo, Phall.',
               'Niveles de picante: suave, ligero, medio, Madras, Vindaloo y Phall.',
               'Schärfegrade: mild, leicht, mittel, Madras, Vindaloo und Phall.'],
        platos: [
          ['Chicken', 'Pollo', 'Hähnchen',
           'Fragrant basmati biryani with chicken.',
           'Biryani de basmati aromático con pollo.',
           'Duftendes Basmati-Biryani mit Hähnchen.',
           '14.95', '87'],
          ['Chicken Tikka', 'Pollo Tikka', 'Hähnchen Tikka',
           'Fragrant basmati biryani with chicken tikka.',
           'Biryani de basmati aromático con pollo Tikka.',
           'Duftendes Basmati-Biryani mit Hähnchen Tikka.',
           '15.95', '88'],
          ['Lamb', 'Cordero', 'Lamm',
           'Fragrant basmati biryani with lamb.',
           'Biryani de basmati aromático con cordero.',
           'Duftendes Basmati-Biryani mit Lamm.',
           '16.95', '89'],
          ['Lamb Tikka', 'Cordero Tikka', 'Lamm Tikka',
           'Fragrant basmati biryani with lamb tikka.',
           'Biryani de basmati aromático con cordero Tikka.',
           'Duftendes Basmati-Biryani mit Lamm Tikka.',
           '17.95', '90'],
          ['Fish', 'Pescado', 'Fisch',
           'Fragrant basmati biryani with fish.',
           'Biryani de basmati aromático con pescado.',
           'Duftendes Basmati-Biryani mit Fisch.',
           '15.95', '91'],
          ['King Prawns', 'Langostinos', 'Riesengarnelen',
           'Fragrant basmati biryani with king prawns.',
           'Biryani de basmati aromático con langostinos.',
           'Duftendes Basmati-Biryani mit Riesengarnelen.',
           '18.95', '92'],
          ['Mixed Special (Chicken, Lamb & Prawn)', 'Especial mixto (pollo, cordero y gambas)', 'Gemischt Spezial (Hähnchen, Lamm und Garnelen)',
           'Fragrant basmati biryani with chicken, lamb and prawn.',
           'Biryani de basmati aromático con pollo, cordero y gambas.',
           'Duftendes Basmati-Biryani mit Hähnchen, Lamm und Garnelen.',
           '19.95', '93'],
          ['Mix Vegetables', 'Verduras variadas', 'Gemischtes Gemüse',
           'Fragrant basmati biryani with mixed vegetables.',
           'Biryani de basmati aromático con verduras variadas.',
           'Duftendes Basmati-Biryani mit gemischtem Gemüse.',
           '14.95', '94'],
          ['Mushrooms', 'Champiñones', 'Champignons',
           'Fragrant basmati biryani with mushrooms.',
           'Biryani de basmati aromático con champiñones.',
           'Duftendes Basmati-Biryani mit Champignons.',
           '14.95', '95'],
          ['Paneer', 'Paneer', 'Paneer',
           'Fragrant basmati biryani with paneer.',
           'Biryani de basmati aromático con paneer.',
           'Duftendes Basmati-Biryani mit Paneer.',
           '15.95', '96'],
          ['Soy', 'Soja', 'Soja',
           'Fragrant basmati biryani with soy.',
           'Biryani de basmati aromático con soja.',
           'Duftendes Basmati-Biryani mit Soja.',
           '16.95', '97'],
          ['Kathal (Raw Jackfruit)', 'Kathal (yaca verde)', 'Kathal (grüne Jackfrucht)',
           'Fragrant basmati biryani with raw jackfruit.',
           'Biryani de basmati aromático con yaca verde.',
           'Duftendes Basmati-Biryani mit grüner Jackfrucht.',
           '16.95', '98'],
        ],
      },
      {
        categoria: 'Butter Masala Biryani',
        subtitulo: ['Butter Masala Biryani', 'Biryani Butter Masala', 'Butter-Masala-Biryani'],
        icono: 'rice',
        platos: [
          ['Chicken Tikka', 'Pollo Tikka', 'Hähnchen Tikka',
           'Creamy butter-masala biryani with chicken tikka.',
           'Biryani cremoso Butter Masala con pollo Tikka.',
           'Cremiges Butter-Masala-Biryani mit Hähnchen Tikka.',
           '19.95', '99'],
          ['Lamb Tikka', 'Cordero Tikka', 'Lamm Tikka',
           'Creamy butter-masala biryani with lamb tikka.',
           'Biryani cremoso Butter Masala con cordero Tikka.',
           'Cremiges Butter-Masala-Biryani mit Lamm Tikka.',
           '17.95', '100'],
          ['Paneer', 'Paneer', 'Paneer',
           'Creamy butter-masala biryani with paneer.',
           'Biryani cremoso Butter Masala con paneer.',
           'Cremiges Butter-Masala-Biryani mit Paneer.',
           '17.95', '101'],
          ['Mixed Special (Chicken, Lamb & Prawn)', 'Especial mixto (pollo, cordero y gambas)', 'Gemischt Spezial (Hähnchen, Lamm und Garnelen)',
           'Creamy butter-masala biryani with chicken, lamb and prawn.',
           'Biryani cremoso Butter Masala con pollo, cordero y gambas.',
           'Cremiges Butter-Masala-Biryani mit Hähnchen, Lamm und Garnelen.',
           '21.95', '102'],
          ['Soy', 'Soja', 'Soja',
           'Creamy butter-masala biryani with soy.',
           'Biryani cremoso Butter Masala con soja.',
           'Cremiges Butter-Masala-Biryani mit Soja.',
           '18.95', '103'],
        ],
      },
    ],
  },
  {
    pestana: ['Breads', 'Panes', 'Brote'],
    icono: 'bread',
    grupos: [
      {
        categoria: 'Naan Bread',
        subtitulo: ['Naan Bread', 'Naan', 'Naan'],
        icono: 'bread',
        nota: ['All naans are egg-free.',
               'Todos los naan se elaboran sin huevo.',
               'Alle Naan werden ohne Ei zubereitet.'],
        platos: [
          ['Plain Naan', 'Naan natural', 'Naan natur',
           'Classic tandoor-baked naan.',
           'Naan clásico hecho en el tandoor.',
           'Klassisches Naan aus dem Tandoor.',
           '3.95', '104'],
          ['Butter Naan', 'Naan con mantequilla', 'Naan mit Butter',
           'Naan finished with butter.',
           'Naan pincelado con mantequilla.',
           'Naan mit Butter bestrichen.',
           '4.50', '105'],
          ['Garlic Naan', 'Naan de ajo', 'Knoblauch-Naan',
           'Naan flavoured with garlic.',
           'Naan al ajo.',
           'Naan mit Knoblauch.',
           '4.50', '106'],
          ['Onion Naan', 'Naan de cebolla', 'Zwiebel-Naan',
           'Naan flavoured with onion.',
           'Naan con cebolla.',
           'Naan mit Zwiebeln.',
           '4.50', '107'],
          ['Chilli Naan', 'Naan de guindilla', 'Chili-Naan',
           'Naan with chilli.',
           'Naan con guindilla.',
           'Naan mit Chili.',
           '4.50', '108'],
          ['Garlic Coriander Naan', 'Naan de ajo y cilantro', 'Naan mit Knoblauch und Koriander',
           'Naan with garlic and coriander.',
           'Naan con ajo y cilantro.',
           'Naan mit Knoblauch und Koriander.',
           '4.50', '109'],
          ['Cheese Naan', 'Naan de queso', 'Käse-Naan',
           'Naan filled or topped with cheese.',
           'Naan relleno o cubierto de queso.',
           'Naan mit Käse gefüllt oder überbacken.',
           '5.00', '110'],
          ['Garlic Cheese Naan', 'Naan de queso y ajo', 'Naan mit Käse und Knoblauch',
           'Cheese naan with garlic.',
           'Naan de queso con ajo.',
           'Käse-Naan mit Knoblauch.',
           '5.00', '111'],
          ['Garlic Chilli Naan', 'Naan de ajo y guindilla', 'Naan mit Knoblauch und Chili',
           'Naan with garlic and chilli.',
           'Naan con ajo y guindilla.',
           'Naan mit Knoblauch und Chili.',
           '5.25', '112'],
          ['Cheese Chilli Naan', 'Naan de queso y guindilla', 'Naan mit Käse und Chili',
           'Cheese naan with chilli.',
           'Naan de queso con guindilla.',
           'Käse-Naan mit Chili.',
           '5.50', '113'],
          ['Garlic Cheese Chilli Naan', 'Naan de ajo, queso y guindilla', 'Naan mit Knoblauch, Käse und Chili',
           'Naan with garlic, cheese and chilli.',
           'Naan con ajo, queso y guindilla.',
           'Naan mit Knoblauch, Käse und Chili.',
           '5.50', '114'],
          ['Peshwari Naan (Coco and Sugar)', 'Naan Peshwari (coco y azúcar)', 'Peshwari-Naan (Kokos und Zucker)',
           'Sweet naan with coconut and sugar.',
           'Naan dulce con coco y azúcar.',
           'Süßes Naan mit Kokos und Zucker.',
           '5.00', '115'],
          ['Kheema Naan (Minced Lamb)', 'Naan Kheema (cordero picado)', 'Kheema-Naan (Lammhack)',
           'Naan stuffed with minced lamb.',
           'Naan relleno de cordero picado.',
           'Naan gefüllt mit Lammhack.',
           '5.50', '116'],
          ['Garlic Kheema Naan (Minced Lamb, Garlic)', 'Naan Kheema con ajo (cordero picado)', 'Kheema-Naan mit Knoblauch (Lammhack)',
           'Minced-lamb naan with garlic.',
           'Naan de cordero picado con ajo.',
           'Lammhack-Naan mit Knoblauch.',
           '5.75', '117'],
          ['Special Kheema Naan (Minced Lamb, Cheese)', 'Naan Kheema especial (cordero picado y queso)', 'Kheema-Naan Spezial (Lammhack und Käse)',
           'Minced-lamb naan with cheese.',
           'Naan de cordero picado con queso.',
           'Lammhack-Naan mit Käse.',
           '5.95', '118'],
        ],
      },
      {
        categoria: 'Flat Breads',
        subtitulo: ['Flat Breads', 'Panes planos', 'Fladenbrote'],
        icono: 'bread',
        platos: [
          ['Tandoori Roti', 'Roti Tandoori', 'Tandoori-Roti',
           'Wheat flatbread cooked in the tandoor.',
           'Pan plano de trigo hecho en el tandoor.',
           'Weizenfladenbrot aus dem Tandoor.',
           '3.95', '119'],
          ['Garlic Tandoori Roti', 'Roti Tandoori de ajo', 'Tandoori-Roti mit Knoblauch',
           'Tandoori roti with garlic.',
           'Roti al tandoor con ajo.',
           'Tandoori-Roti mit Knoblauch.',
           '4.50', '120'],
          ['Garlic Chilli Tandoori Roti', 'Roti Tandoori de ajo y guindilla', 'Tandoori-Roti mit Knoblauch und Chili',
           'Tandoori roti with garlic and chilli.',
           'Roti al tandoor con ajo y guindilla.',
           'Tandoori-Roti mit Knoblauch und Chili.',
           '5.25', '121'],
          ['Plain Chapati', 'Chapati natural', 'Chapati natur',
           'Unleavened wheat flatbread cooked on a griddle.',
           'Pan plano de trigo sin levadura, hecho a la plancha.',
           'Ungesäuertes Weizenfladenbrot von der Platte.',
           '3.00', '122'],
          ['Butter Chapati', 'Chapati con mantequilla', 'Chapati mit Butter',
           'Chapati finished with butter.',
           'Chapati pincelado con mantequilla.',
           'Chapati mit Butter bestrichen.',
           '3.25', '123'],
          ['Garlic Chapati', 'Chapati de ajo', 'Chapati mit Knoblauch',
           'Chapati with garlic.',
           'Chapati con ajo.',
           'Chapati mit Knoblauch.',
           '3.50', '124'],
          ['Aloo Paratha (Stuffed with Spiced Potatoes)', 'Aloo Paratha (relleno de patata especiada)', 'Aloo Paratha (gefüllt mit gewürzten Kartoffeln)',
           'Layered flatbread stuffed with spiced potato.',
           'Pan plano hojaldrado relleno de patata especiada.',
           'Blättriges Fladenbrot mit gewürzter Kartoffelfüllung.',
           '4.90', '125'],
          ['Stuffed Paratha (Spiced Potato & Paneer)', 'Paratha relleno (patata especiada y paneer)', 'Gefülltes Paratha (Kartoffel und Paneer)',
           'Layered flatbread stuffed with potato and paneer.',
           'Pan plano hojaldrado relleno de patata y paneer.',
           'Blättriges Fladenbrot mit Kartoffel- und Paneerfüllung.',
           '5.50', '126'],
        ],
      },
    ],
  },
  {
    pestana: ['Rice & Fries', 'Arroces y patatas', 'Reis & Pommes'],
    icono: 'fries',
    grupos: [
      {
        categoria: 'Indian Rice',
        subtitulo: ['Indian Rice', 'Arroz basmati', 'Basmatireis'],
        icono: 'rice',
        nota: ['All rice dishes use Indian basmati rice.',
               'Todos los arroces se preparan con basmati indio.',
               'Alle Reisgerichte werden mit indischem Basmatireis zubereitet.'],
        platos: [
          ['Plain Boiled Rice', 'Arroz basmati hervido', 'Basmatireis',
           'Steamed basmati rice.',
           'Arroz basmati al vapor.',
           'Gedämpfter Basmatireis.',
           '4.00', '127'],
          ['Pilao Rice', 'Arroz Pilao', 'Pilao-Reis',
           'Basmati rice cooked with spices.',
           'Arroz basmati cocinado con especias.',
           'Basmatireis mit Gewürzen.',
           '4.25', '128'],
          ['Cumin Rice', 'Arroz al comino', 'Reis mit Kreuzkümmel',
           'Basmati rice flavoured with cumin.',
           'Arroz basmati al comino.',
           'Basmatireis mit Kreuzkümmel.',
           '4.50', '129'],
          ['Garlic Rice', 'Arroz al ajo', 'Knoblauchreis',
           'Basmati rice flavoured with garlic.',
           'Arroz basmati al ajo.',
           'Basmatireis mit Knoblauch.',
           '4.50', '130'],
          ['Onion Rice', 'Arroz con cebolla', 'Reis mit Zwiebeln',
           'Basmati rice with onion.',
           'Arroz basmati con cebolla.',
           'Basmatireis mit Zwiebeln.',
           '4.50', '131'],
          ['Egg Rice', 'Arroz con huevo', 'Reis mit Ei',
           'Basmati rice with egg.',
           'Arroz basmati con huevo.',
           'Basmatireis mit Ei.',
           '4.50', '132'],
          ['Green Peas Pulao Rice', 'Arroz Pulao con guisantes', 'Pulao-Reis mit Erbsen',
           'Pulao rice with green peas.',
           'Arroz Pulao con guisantes.',
           'Pulao-Reis mit grünen Erbsen.',
           '4.95', '133'],
          ['Lemon Rice', 'Arroz al limón', 'Zitronenreis',
           'Basmati rice with lemon.',
           'Arroz basmati al limón.',
           'Basmatireis mit Zitrone.',
           '4.95', '134'],
          ['Mushroom Rice', 'Arroz con champiñones', 'Reis mit Champignons',
           'Basmati rice with mushrooms.',
           'Arroz basmati con champiñones.',
           'Basmatireis mit Champignons.',
           '4.50', '135'],
          ['Mixed Vegetable Rice', 'Arroz con verduras', 'Reis mit Gemüse',
           'Basmati rice with mixed vegetables.',
           'Arroz basmati con verduras variadas.',
           'Basmatireis mit gemischtem Gemüse.',
           '4.95', '136'],
          ['Coco Rice', 'Arroz con coco', 'Kokosreis',
           'Basmati rice with coconut.',
           'Arroz basmati con coco.',
           'Basmatireis mit Kokos.',
           '4.95', '137'],
          ['Kheema Rice', 'Arroz Kheema', 'Kheema-Reis',
           'Basmati rice with seasoned minced meat.',
           'Arroz basmati con carne picada especiada.',
           'Basmatireis mit gewürztem Hackfleisch.',
           '4.50', '138'],
          ['Special Rice (Prawns with Vegetables)', 'Arroz especial (gambas y verduras)', 'Reis Spezial (Garnelen und Gemüse)',
           'Basmati rice with prawns and vegetables.',
           'Arroz basmati con gambas y verduras.',
           'Basmatireis mit Garnelen und Gemüse.',
           '7.50', '139'],
        ],
      },
      {
        categoria: 'Fries',
        subtitulo: ['Fries', 'Patatas', 'Pommes frites'],
        icono: 'fries',
        platos: [
          ['French Fries', 'Patatas fritas', 'Pommes frites',
           'Classic fries.',
           'Patatas fritas clásicas.',
           'Klassische Pommes frites.',
           '3.50', '140'],
          ['Masala Fries', 'Patatas fritas Masala', 'Masala-Pommes',
           'Fries seasoned with masala spices.',
           'Patatas fritas con especias masala.',
           'Pommes frites mit Masala-Gewürzen.',
           '4.50', '141'],
        ],
      },
    ],
  },
  {
    pestana: ['Kids', 'Niños', 'Für Kinder'],
    icono: 'kids',
    grupos: [
      {
        categoria: 'Kids Menu',
        subtitulo: null,
        nota: ['Only served for children under 9 years.',
               'Solo para menores de 9 años.',
               'Nur für Kinder unter 9 Jahren.'],
        platos: [
          ['French Omelette and Chips', 'Tortilla francesa con patatas', 'Omelett mit Pommes frites',
           'French omelette served with chips.',
           'Tortilla francesa con patatas fritas.',
           'Omelett mit Pommes frites.',
           '6.00', '142'],
          ['Chicken Nuggets and Chips', 'Nuggets de pollo con patatas', 'Hähnchen-Nuggets mit Pommes frites',
           'Chicken nuggets served with chips.',
           'Nuggets de pollo con patatas fritas.',
           'Hähnchen-Nuggets mit Pommes frites.',
           '6.00', '143'],
          ['Chicken Tikka with Chips or Rice', 'Pollo Tikka con patatas o arroz', 'Hähnchen Tikka mit Pommes oder Reis',
           'Diced chicken tikka with chips or rice.',
           'Pollo Tikka en dados con patatas fritas o arroz.',
           'Hähnchen Tikka in Würfeln, mit Pommes oder Reis.',
           '8.00', '144'],
          ['Chicken Korma with Chips or Rice', 'Pollo Korma con patatas o arroz', 'Hähnchen Korma mit Pommes oder Reis',
           'Mild creamy chicken korma with chips or rice.',
           'Pollo Korma suave y cremoso con patatas fritas o arroz.',
           'Mildes, cremiges Hähnchen Korma mit Pommes oder Reis.',
           '8.50', '145'],
          ['Chicken Tikka Masala with Chips or Rice', 'Pollo Tikka Masala con patatas o arroz', 'Hähnchen Tikka Masala mit Pommes oder Reis',
           'Mild chicken tikka masala with chips or rice.',
           'Pollo Tikka Masala suave con patatas fritas o arroz.',
           'Mildes Hähnchen Tikka Masala mit Pommes oder Reis.',
           '8.50', '146'],
          ['Chicken Curry with Chips or Rice', 'Pollo al curry con patatas o arroz', 'Hähnchen-Curry mit Pommes oder Reis',
           'Mild chicken curry with chips or rice.',
           'Pollo al curry suave con patatas fritas o arroz.',
           'Mildes Hähnchencurry mit Pommes oder Reis.',
           '8.50', '147'],
          ['Paneer Tikka Masala with Chips or Rice', 'Paneer Tikka Masala con patatas o arroz', 'Paneer Tikka Masala mit Pommes oder Reis',
           'Mild paneer tikka masala with chips or rice.',
           'Paneer Tikka Masala suave con patatas fritas o arroz.',
           'Mildes Paneer Tikka Masala mit Pommes oder Reis.',
           '8.50', '148'],
        ],
      },
    ],
  },
  {
    pestana: ['Gluten Free', 'Sin gluten', 'Glutenfrei'],
    icono: 'gf',
    grupos: [
      {
        categoria: 'Gluten Free - Soups',
        subtitulo: ['Soups', 'Sopas', 'Suppen'],
        icono: 'soup',
        platos: [
          ['Lentil Soup', 'Sopa de lentejas', 'Linsensuppe',
           'Gluten-free lentil soup.',
           'Sopa de lentejas sin gluten.',
           'Glutenfreie Linsensuppe.',
           '8.00', ''],
          ['Tomato Soup', 'Sopa de tomate', 'Tomatensuppe',
           'Gluten-free tomato soup.',
           'Crema de tomate sin gluten.',
           'Glutenfreie Tomatensuppe.',
           '7.50', ''],
          ['Chicken Soup', 'Sopa de pollo', 'Hühnersuppe',
           'Gluten-free chicken soup.',
           'Sopa de pollo sin gluten.',
           'Glutenfreie Hühnersuppe.',
           '8.50', ''],
        ],
      },
      {
        categoria: 'Gluten Free - Salads',
        subtitulo: ['Salads', 'Ensaladas', 'Salate'],
        icono: 'salad',
        platos: [
          ['Garden Salad', 'Ensalada de la huerta', 'Gartensalat',
           'Fresh mixed salad.',
           'Ensalada fresca variada.',
           'Frischer gemischter Salat.',
           '6.00', ''],
          ['Sprouts Salad', 'Ensalada de brotes', 'Sprossensalat',
           'Sprouted-legume salad.',
           'Ensalada de legumbres germinadas.',
           'Salat aus gekeimten Hülsenfrüchten.',
           '12.95', ''],
          ['Turmeric Quinoa & Chickpea Salad', 'Ensalada de quinoa con cúrcuma y garbanzos', 'Kurkuma-Quinoa-Salat mit Kichererbsen',
           'Quinoa and chickpea salad with turmeric.',
           'Ensalada de quinoa y garbanzos con cúrcuma.',
           'Quinoa-Kichererbsen-Salat mit Kurkuma.',
           '13.95', ''],
          ['Tandoori Paneer Salad', 'Ensalada de paneer Tandoori', 'Salat mit Tandoori-Paneer',
           'Salad with tandoori paneer.',
           'Ensalada con paneer al tandoor.',
           'Salat mit Tandoori-Paneer.',
           '15.95', ''],
          ['Tandoori Prawns Salad', 'Ensalada de gambas Tandoori', 'Salat mit Tandoori-Garnelen',
           'Salad with tandoori prawns.',
           'Ensalada con gambas al tandoor.',
           'Salat mit Tandoori-Garnelen.',
           '15.95', ''],
        ],
      },
      {
        categoria: 'Gluten Free - Starters',
        subtitulo: ['Starters', 'Entrantes', 'Vorspeisen'],
        icono: 'meat',
        platos: [
          ['Katori Chaat', 'Katori Chaat', 'Katori Chaat',
           'Gluten-free chaat preparation.',
           'Chaat en versión sin gluten.',
           'Chaat in glutenfreier Zubereitung.',
           '9.95', ''],
          ['Aloo Tikki Chaat', 'Aloo Tikki Chaat', 'Aloo Tikki Chaat',
           'Gluten-free potato tikki chaat.',
           'Chaat de tikki de patata sin gluten.',
           'Glutenfreies Kartoffel-Tikki-Chaat.',
           '9.95', ''],
          ['Cauliflower Wings', 'Alitas de coliflor', 'Blumenkohl-Wings',
           'Gluten-free cauliflower wings.',
           'Alitas de coliflor sin gluten.',
           'Glutenfreie Blumenkohl-Wings.',
           '9.95', ''],
          ['Chutney Bombs', 'Bombas de chutney', 'Chutney-Bällchen',
           'Gluten-free paneer-and-potato bites.',
           'Bocaditos de paneer y patata sin gluten.',
           'Glutenfreie Paneer-Kartoffel-Bällchen.',
           '9.95', ''],
          ['Tandoori Malai Broccoli', 'Brócoli Tandoori Malai', 'Tandoori Malai Brokkoli',
           'Gluten-free tandoori broccoli.',
           'Brócoli al tandoor sin gluten.',
           'Glutenfreier Tandoori-Brokkoli.',
           '10.00', ''],
          ['Fish Pakora', 'Pakora de pescado', 'Fisch-Pakora',
           'Gluten-free fried fish starter.',
           'Entrante de pescado frito sin gluten.',
           'Glutenfreie Vorspeise mit frittiertem Fisch.',
           '9.95', ''],
          ['Garlic Prawns', 'Gambas al ajillo', 'Knoblauchgarnelen',
           'Garlic prawns.',
           'Gambas al ajillo.',
           'Knoblauchgarnelen.',
           '9.95', ''],
          ['Gluten Free Puri - Chicken', 'Puri sin gluten con pollo', 'Glutenfreies Puri mit Hähnchen',
           'Chicken served with gluten-free fried puri.',
           'Pollo servido con puri frito sin gluten.',
           'Hähnchen mit glutenfreiem frittiertem Puri.',
           '8.95', ''],
          ['Gluten Free Puri - Prawns', 'Puri sin gluten con gambas', 'Glutenfreies Puri mit Garnelen',
           'Prawns served with gluten-free fried puri.',
           'Gambas servidas con puri frito sin gluten.',
           'Garnelen mit glutenfreiem frittiertem Puri.',
           '9.95', ''],
        ],
      },
      {
        categoria: 'Gluten Free - Curries',
        subtitulo: ['Curries', 'Currys', 'Currys'],
        icono: 'bowl',
        nota: ['Classic sauces: Butter Masala, Tikka Masala, Korma, Kashmiri, Madras, Balti, Jalfrezi, Bhuna, Dopiaza, Curry, Dhansak, Saag, Kashmiri Rogan Josh. South Indian sauces: Kadai, Madras, Garlic Chilli, Hyderabadi Handi, Chettinad, Malabar Curry, Goan Vindaloo.',
               'Salsas clásicas: Butter Masala, Tikka Masala, Korma, Kashmiri, Madras, Balti, Jalfrezi, Bhuna, Dopiaza, Curry, Dhansak, Saag y Kashmiri Rogan Josh. Salsas del sur de la India: Kadai, Madras, ajo y guindilla, Hyderabadi Handi, Chettinad, Malabar y Vindaloo de Goa.',
               'Klassische Saucen: Butter Masala, Tikka Masala, Korma, Kashmiri, Madras, Balti, Jalfrezi, Bhuna, Dopiaza, Curry, Dhansak, Saag und Kashmiri Rogan Josh. Südindische Saucen: Kadai, Madras, Knoblauch-Chili, Hyderabadi Handi, Chettinad, Malabar und Vindaloo aus Goa.'],
        platos: [
          ['Chicken', 'Pollo', 'Hähnchen',
           'Choose a gluten-free curry sauce.',
           'Elige una salsa de curry sin gluten.',
           'Eine glutenfreie Currysauce wählen.',
           '14.95', ''],
          ['Lamb', 'Cordero', 'Lamm',
           'Choose a gluten-free curry sauce.',
           'Elige una salsa de curry sin gluten.',
           'Eine glutenfreie Currysauce wählen.',
           '16.95', ''],
          ['Fish', 'Pescado', 'Fisch',
           'Choose a gluten-free curry sauce.',
           'Elige una salsa de curry sin gluten.',
           'Eine glutenfreie Currysauce wählen.',
           '15.95', ''],
          ['Prawns', 'Gambas', 'Garnelen',
           'Choose a gluten-free curry sauce.',
           'Elige una salsa de curry sin gluten.',
           'Eine glutenfreie Currysauce wählen.',
           '16.95', ''],
          ['King Prawns', 'Langostinos', 'Riesengarnelen',
           'Choose a gluten-free curry sauce.',
           'Elige una salsa de curry sin gluten.',
           'Eine glutenfreie Currysauce wählen.',
           '18.95', ''],
          ['Paneer', 'Paneer', 'Paneer',
           'Choose a gluten-free curry sauce.',
           'Elige una salsa de curry sin gluten.',
           'Eine glutenfreie Currysauce wählen.',
           '15.95', ''],
          ['Mixed Vegetables', 'Verduras variadas', 'Gemischtes Gemüse',
           'Choose a gluten-free curry sauce.',
           'Elige una salsa de curry sin gluten.',
           'Eine glutenfreie Currysauce wählen.',
           '13.95', ''],
          ['Mushrooms', 'Champiñones', 'Champignons',
           'Choose a gluten-free curry sauce.',
           'Elige una salsa de curry sin gluten.',
           'Eine glutenfreie Currysauce wählen.',
           '13.95', ''],
          ['Kathal (Raw Jackfruit)', 'Kathal (yaca verde)', 'Kathal (grüne Jackfrucht)',
           'Choose a gluten-free curry sauce.',
           'Elige una salsa de curry sin gluten.',
           'Eine glutenfreie Currysauce wählen.',
           '16.95', ''],
        ],
      },
      {
        categoria: 'Gluten Free - Sizzlers',
        subtitulo: ['Sizzlers', 'A la plancha', 'Vom heißen Eisen'],
        icono: 'flame',
        platos: [
          ['Fish Shashlik Sizzler', 'Shashlik de pescado a la plancha', 'Fisch-Shashlik vom heißen Eisen',
           'Gluten-free fish shashlik.',
           'Shashlik de pescado sin gluten.',
           'Glutenfreies Fisch-Shashlik.',
           '21.95', ''],
          ['Paneer Shashlik Sizzler', 'Shashlik de paneer a la plancha', 'Paneer-Shashlik vom heißen Eisen',
           'Gluten-free paneer shashlik.',
           'Shashlik de paneer sin gluten.',
           'Glutenfreies Paneer-Shashlik.',
           '17.95', ''],
          ['Kathal Shashlik Sizzler', 'Shashlik de Kathal a la plancha', 'Kathal-Shashlik vom heißen Eisen',
           'Gluten-free jackfruit shashlik.',
           'Shashlik de yaca sin gluten.',
           'Glutenfreies Jackfrucht-Shashlik.',
           '18.95', ''],
        ],
      },
      {
        categoria: 'Gluten Free - Biryani',
        subtitulo: ['Biryani', 'Biryani', 'Biryani'],
        icono: 'rice',
        platos: [
          ['Chicken', 'Pollo', 'Hähnchen',
           'Gluten-free biryani with chicken.',
           'Biryani sin gluten con pollo.',
           'Glutenfreies Biryani mit Hähnchen.',
           '16.95', ''],
          ['Lamb', 'Cordero', 'Lamm',
           'Gluten-free biryani with lamb.',
           'Biryani sin gluten con cordero.',
           'Glutenfreies Biryani mit Lamm.',
           '18.95', ''],
          ['Fish', 'Pescado', 'Fisch',
           'Gluten-free biryani with fish.',
           'Biryani sin gluten con pescado.',
           'Glutenfreies Biryani mit Fisch.',
           '17.95', ''],
          ['King Prawns', 'Langostinos', 'Riesengarnelen',
           'Gluten-free biryani with king prawns.',
           'Biryani sin gluten con langostinos.',
           'Glutenfreies Biryani mit Riesengarnelen.',
           '19.95', ''],
          ['Paneer', 'Paneer', 'Paneer',
           'Gluten-free biryani with paneer.',
           'Biryani sin gluten con paneer.',
           'Glutenfreies Biryani mit Paneer.',
           '17.95', ''],
          ['Mixed Vegetables', 'Verduras variadas', 'Gemischtes Gemüse',
           'Gluten-free vegetable biryani.',
           'Biryani de verduras sin gluten.',
           'Glutenfreies Gemüse-Biryani.',
           '16.95', ''],
          ['Mushrooms', 'Champiñones', 'Champignons',
           'Gluten-free mushroom biryani.',
           'Biryani de champiñones sin gluten.',
           'Glutenfreies Champignon-Biryani.',
           '16.95', ''],
          ['Kathal (Raw Jackfruit)', 'Kathal (yaca verde)', 'Kathal (grüne Jackfrucht)',
           'Gluten-free jackfruit biryani.',
           'Biryani de yaca sin gluten.',
           'Glutenfreies Jackfrucht-Biryani.',
           '18.95', ''],
        ],
      },
      {
        categoria: 'Gluten Free - Vegetable & Lentil Dishes',
        subtitulo: ['Vegetable & Lentil Dishes', 'Verduras y lentejas', 'Gemüse & Linsen'],
        icono: 'lentils',
        platos: [
          ['Bombay Aloo', 'Bombay Aloo', 'Bombay Aloo',
           'Gluten-free potato dish.',
           'Plato de patata sin gluten.',
           'Glutenfreies Kartoffelgericht.',
           '11.95', ''],
          ['Aloo Gobhi', 'Aloo Gobhi', 'Aloo Gobhi',
           'Gluten-free potato and cauliflower dish.',
           'Plato de patata y coliflor sin gluten.',
           'Glutenfreies Gericht mit Kartoffel und Blumenkohl.',
           '11.95', ''],
          ['Saag Aloo', 'Saag Aloo', 'Saag Aloo',
           'Gluten-free spinach and potato dish.',
           'Plato de espinacas y patata sin gluten.',
           'Glutenfreies Gericht mit Spinat und Kartoffel.',
           '11.95', ''],
          ['Chana Masala', 'Chana Masala', 'Chana Masala',
           'Gluten-free chickpea curry.',
           'Curry de garbanzos sin gluten.',
           'Glutenfreies Kichererbsencurry.',
           '12.95', ''],
          ['Bhindi Masala', 'Bhindi Masala', 'Bhindi Masala',
           'Gluten-free okra dish.',
           'Plato de okra sin gluten.',
           'Glutenfreies Okragericht.',
           '13.95', ''],
          ['Malai Kofta', 'Malai Kofta', 'Malai Kofta',
           'Gluten-free malai kofta.',
           'Malai Kofta sin gluten.',
           'Glutenfreies Malai Kofta.',
           '15.95', ''],
          ['Mutter Paneer', 'Mutter Paneer', 'Mutter Paneer',
           'Gluten-free paneer and peas.',
           'Paneer con guisantes sin gluten.',
           'Glutenfreier Paneer mit Erbsen.',
           '15.95', ''],
          ['Palak Paneer', 'Palak Paneer', 'Palak Paneer',
           'Gluten-free paneer and spinach.',
           'Paneer con espinacas sin gluten.',
           'Glutenfreier Paneer mit Spinat.',
           '15.95', ''],
          ['Navratan Korma', 'Navratan Korma', 'Navratan Korma',
           'Gluten-free mixed vegetable korma.',
           'Korma de verduras sin gluten.',
           'Glutenfreies Gemüse-Korma.',
           '15.95', ''],
          ['Yellow Dal Tadka', 'Dal Tadka amarillo', 'Gelbes Dal Tadka',
           'Gluten-free yellow lentils.',
           'Lentejas amarillas sin gluten.',
           'Glutenfreie gelbe Linsen.',
           '12.95', ''],
          ['Dal Makhani', 'Dal Makhani', 'Dal Makhani',
           'Gluten-free black lentils.',
           'Lentejas negras sin gluten.',
           'Glutenfreie schwarze Linsen.',
           '14.95', ''],
          ['Palak Dal (Spinach)', 'Palak Dal (espinacas)', 'Palak Dal (Spinat)',
           'Gluten-free spinach lentils.',
           'Lentejas con espinacas sin gluten.',
           'Glutenfreie Linsen mit Spinat.',
           '14.95', ''],
        ],
      },
      {
        categoria: 'Gluten Free - Rice, Fries & Breads',
        subtitulo: ['Rice, Fries & Breads', 'Arroz, patatas y panes', 'Reis, Pommes & Brote'],
        icono: 'rice',
        platos: [
          ['Plain Boiled Rice', 'Arroz basmati hervido', 'Basmatireis',
           'Steamed basmati rice.',
           'Arroz basmati al vapor.',
           'Gedämpfter Basmatireis.',
           '4.00', ''],
          ['Pilao Rice', 'Arroz Pilao', 'Pilao-Reis',
           'Spiced basmati rice.',
           'Arroz basmati especiado.',
           'Gewürzter Basmatireis.',
           '4.25', ''],
          ['Cumin Rice', 'Arroz al comino', 'Reis mit Kreuzkümmel',
           'Cumin basmati rice.',
           'Arroz basmati al comino.',
           'Basmatireis mit Kreuzkümmel.',
           '4.50', ''],
          ['Garlic Rice', 'Arroz al ajo', 'Knoblauchreis',
           'Garlic basmati rice.',
           'Arroz basmati al ajo.',
           'Basmatireis mit Knoblauch.',
           '4.50', ''],
          ['Onion Rice', 'Arroz con cebolla', 'Reis mit Zwiebeln',
           'Onion basmati rice.',
           'Arroz basmati con cebolla.',
           'Basmatireis mit Zwiebeln.',
           '4.50', ''],
          ['Egg Rice', 'Arroz con huevo', 'Reis mit Ei',
           'Basmati rice with egg.',
           'Arroz basmati con huevo.',
           'Basmatireis mit Ei.',
           '4.95', ''],
          ['Green Peas Pulao Rice', 'Arroz Pulao con guisantes', 'Pulao-Reis mit Erbsen',
           'Pea pulao rice.',
           'Arroz Pulao con guisantes.',
           'Pulao-Reis mit Erbsen.',
           '4.95', ''],
          ['Lemon Rice', 'Arroz al limón', 'Zitronenreis',
           'Lemon basmati rice.',
           'Arroz basmati al limón.',
           'Basmatireis mit Zitrone.',
           '4.50', ''],
          ['Mushroom Rice', 'Arroz con champiñones', 'Reis mit Champignons',
           'Mushroom basmati rice.',
           'Arroz basmati con champiñones.',
           'Basmatireis mit Champignons.',
           '4.95', ''],
          ['Mixed Vegetable Rice', 'Arroz con verduras', 'Reis mit Gemüse',
           'Vegetable basmati rice.',
           'Arroz basmati con verduras.',
           'Basmatireis mit Gemüse.',
           '4.95', ''],
          ['Coco Rice', 'Arroz con coco', 'Kokosreis',
           'Coconut basmati rice.',
           'Arroz basmati con coco.',
           'Basmatireis mit Kokos.',
           '4.50', ''],
          ['Special Rice (Prawns & Veg)', 'Arroz especial (gambas y verduras)', 'Reis Spezial (Garnelen und Gemüse)',
           'Rice with prawns and vegetables.',
           'Arroz con gambas y verduras.',
           'Reis mit Garnelen und Gemüse.',
           '7.50', ''],
          ['French Fries', 'Patatas fritas', 'Pommes frites',
           'Gluten-free fries.',
           'Patatas fritas sin gluten.',
           'Glutenfreie Pommes frites.',
           '4.50', ''],
          ['Masala Fries', 'Patatas fritas Masala', 'Masala-Pommes',
           'Gluten-free masala-seasoned fries.',
           'Patatas fritas con especias masala, sin gluten.',
           'Glutenfreie Pommes mit Masala-Gewürzen.',
           '5.50', ''],
          ['Gluten Free Chapati', 'Chapati sin gluten', 'Glutenfreies Chapati',
           'Gluten-free chapati.',
           'Chapati sin gluten.',
           'Glutenfreies Chapati.',
           '3.95', ''],
          ['Vegan Gluten Free Chapati', 'Chapati vegano sin gluten', 'Veganes glutenfreies Chapati',
           'Vegan and gluten-free chapati.',
           'Chapati vegano y sin gluten.',
           'Veganes und glutenfreies Chapati.',
           '4.50', ''],
        ],
      },
      {
        categoria: 'Gluten Free - Special Dishes',
        subtitulo: ['Special Dishes', 'Platos especiales', 'Spezialgerichte'],
        icono: 'special',
        platos: [
          ['Kheema Peas', 'Kheema con guisantes', 'Kheema mit Erbsen',
           'Minced meat and peas, gluten-free preparation.',
           'Carne picada con guisantes, elaboración sin gluten.',
           'Hackfleisch mit Erbsen, glutenfrei zubereitet.',
           '17.95', ''],
          ['Bhindi Gosht', 'Bhindi Gosht', 'Bhindi Gosht',
           'Lamb and okra, gluten-free preparation.',
           'Cordero con okra, elaboración sin gluten.',
           'Lamm mit Okra, glutenfrei zubereitet.',
           '17.95', ''],
        ],
      },
    ],
  },
  {
    pestana: ['Vegan', 'Vegano', 'Vegan'],
    icono: 'vegetarian',
    intro: ['Prepared using vegan alternatives such as plant-based butter, cream, yoghurt and milk.',
            'Preparado utilizando alternativas veganas como mantequilla, crema, yogur y leche de origen vegetal.',
            'Zubereitet mit veganen Alternativen wie pflanzlicher Butter, Sahne, Joghurt und Milch.'],
    grupos: [
      {
        categoria: 'Vegan - Appetizers',
        subtitulo: ['Appetizers', 'Aperitivos', 'Kleinigkeiten'],
        icono: 'appetizers',
        platos: [
          ['Papadum', 'Papadum', 'Papadum',
           'Crisp lentil wafer.',
           'Oblea crujiente de lenteja.',
           'Knuspriger Linsenfladen.',
           '1.00', ''],
          ['Spicy Papadum', 'Papadum especiado', 'Papadum mit Gewürzen',
           'Spiced crisp lentil wafer.',
           'Oblea crujiente de lenteja con especias.',
           'Knuspriger Linsenfladen mit Gewürzen.',
           '1.00', ''],
          ['Vegan Pickle Tray', 'Surtido de encurtidos vegano', 'Vegane Pickle-Auswahl',
           'Mango, vegan mint sauce and onions.',
           'Mango, salsa vegana de menta y cebolla.',
           'Mango, vegane Minzsauce und Zwiebeln.',
           '4.00', ''],
          ['Vegan Mix Raita', 'Raita vegana de verduras', 'Veganes Gemüse-Raita',
           'Plant-based raita.',
           'Raita de base vegetal.',
           'Raita auf pflanzlicher Basis.',
           '4.50', ''],
        ],
      },
      {
        categoria: 'Vegan - Soups',
        subtitulo: ['Soups', 'Sopas', 'Suppen'],
        icono: 'soup',
        platos: [
          ['Lentil Soup', 'Sopa de lentejas', 'Linsensuppe',
           'Plant-based lentil soup.',
           'Sopa de lentejas de base vegetal.',
           'Linsensuppe auf pflanzlicher Basis.',
           '8.00', ''],
          ['Tomato Soup', 'Sopa de tomate', 'Tomatensuppe',
           'Plant-based tomato soup.',
           'Crema de tomate de base vegetal.',
           'Tomatensuppe auf pflanzlicher Basis.',
           '7.50', ''],
        ],
      },
      {
        categoria: 'Vegan - Salads',
        subtitulo: ['Salads', 'Ensaladas', 'Salate'],
        icono: 'salad',
        platos: [
          ['Garden Salad', 'Ensalada de la huerta', 'Gartensalat',
           'Fresh mixed salad.',
           'Ensalada fresca variada.',
           'Frischer gemischter Salat.',
           '6.00', ''],
          ['Sprouts Salad', 'Ensalada de brotes', 'Sprossensalat',
           'Sprouted-legume salad.',
           'Ensalada de legumbres germinadas.',
           'Salat aus gekeimten Hülsenfrüchten.',
           '11.95', ''],
          ['Turmeric Quinoa & Chickpea', 'Quinoa con cúrcuma y garbanzos', 'Kurkuma-Quinoa mit Kichererbsen',
           'Turmeric quinoa and chickpea salad.',
           'Ensalada de quinoa a la cúrcuma con garbanzos.',
           'Kurkuma-Quinoa-Salat mit Kichererbsen.',
           '12.95', ''],
          ['Tofu Salad', 'Ensalada de tofu', 'Tofu-Salat',
           'Salad with tofu.',
           'Ensalada con tofu.',
           'Salat mit Tofu.',
           '14.95', ''],
          ['Crunchy Vegan Meat Salad', 'Ensalada de carne vegana crujiente', 'Salat mit knusprigem veganem Fleisch',
           'Salad with soy-based vegan protein.',
           'Ensalada con proteína vegana de soja.',
           'Salat mit veganem Sojaprotein.',
           '15.95', ''],
          ['Tandoori Jackfruit Salad', 'Ensalada de yaca Tandoori', 'Salat mit Tandoori-Jackfrucht',
           'Salad with tandoori jackfruit.',
           'Ensalada con yaca al tandoor.',
           'Salat mit Tandoori-Jackfrucht.',
           '15.95', ''],
        ],
      },
      {
        categoria: 'Vegan - Starters',
        subtitulo: ['Starters', 'Entrantes', 'Vorspeisen'],
        icono: 'vegetarian',
        platos: [
          ['Onion Pakora', 'Pakora de cebolla', 'Zwiebel-Pakora',
           'Vegan onion fritters.',
           'Buñuelos veganos de cebolla.',
           'Vegane Zwiebelkrapfen.',
           '6.50', ''],
          ['Spinach Pakora', 'Pakora de espinacas', 'Spinat-Pakora',
           'Vegan spinach fritters.',
           'Buñuelos veganos de espinaca.',
           'Vegane Spinatkrapfen.',
           '7.00', ''],
          ['Raw Plantain Pakora', 'Pakora de plátano macho', 'Kochbananen-Pakora',
           'Vegan plantain fritters.',
           'Buñuelos veganos de plátano macho.',
           'Vegane Kochbananenkrapfen.',
           '7.00', ''],
          ['Vegetable Samosa', 'Samosa de verduras', 'Gemüse-Samosa',
           'Vegan vegetable samosa.',
           'Samosa vegana de verduras.',
           'Vegane Gemüse-Samosa.',
           '6.00', ''],
          ['Katori Chaat', 'Katori Chaat', 'Katori Chaat',
           'Chaat topped with plant-based yogurt and chutneys.',
           'Chaat con yogur vegetal y chutneys.',
           'Chaat mit pflanzlichem Joghurt und Chutneys.',
           '9.95', ''],
          ['Aloo Tikki Chaat', 'Aloo Tikki Chaat', 'Aloo Tikki Chaat',
           'Potato patties with plant-based yogurt, chutneys and sev.',
           'Tortitas de patata con yogur vegetal, chutneys y sev.',
           'Kartoffelplätzchen mit pflanzlichem Joghurt, Chutneys und Sev.',
           '9.95', ''],
          ['Cauliflower Wings', 'Alitas de coliflor', 'Blumenkohl-Wings',
           'Crispy cauliflower with vegan garlic mayonnaise.',
           'Coliflor crujiente con mayonesa vegana de ajo.',
           'Knuspriger Blumenkohl mit veganer Knoblauchmayonnaise.',
           '9.00', ''],
          ['Soy Puri', 'Puri de soja', 'Soja-Puri',
           'Soy filling served with fried puri.',
           'Relleno de soja servido con puri frito.',
           'Sojafüllung mit frittiertem Puri.',
           '9.00', ''],
          ['Vegan Platter', 'Surtido vegano', 'Vegane Platte',
           'Mixed vegan starter platter.',
           'Surtido de entrantes veganos.',
           'Gemischte vegane Vorspeisenplatte.',
           '19.95', ''],
        ],
      },
      {
        categoria: 'Vegan - Curries',
        subtitulo: ['Curries', 'Currys', 'Currys'],
        icono: 'bowl',
        nota: ['Classic sauces: Butter Masala, Tikka Masala, Korma, Kashmiri, Madras, Balti, Jalfrezi, Bhuna, Dopiaza, Curry, Dhansak, Saag, Kashmiri Rogan Josh. South Indian sauces: Kadai, Madras, Garlic Chilli, Hyderabadi Handi, Chettinad, Malabar Curry, Goan Vindaloo. Spice levels: Mild, Touch, Medium, Madras, Vindaloo, Phall.',
               'Salsas clásicas: Butter Masala, Tikka Masala, Korma, Kashmiri, Madras, Balti, Jalfrezi, Bhuna, Dopiaza, Curry, Dhansak, Saag y Kashmiri Rogan Josh. Salsas del sur de la India: Kadai, Madras, ajo y guindilla, Hyderabadi Handi, Chettinad, Malabar y Vindaloo de Goa. Niveles de picante: suave, ligero, medio, Madras, Vindaloo y Phall.',
               'Klassische Saucen: Butter Masala, Tikka Masala, Korma, Kashmiri, Madras, Balti, Jalfrezi, Bhuna, Dopiaza, Curry, Dhansak, Saag und Kashmiri Rogan Josh. Südindische Saucen: Kadai, Madras, Knoblauch-Chili, Hyderabadi Handi, Chettinad, Malabar und Vindaloo aus Goa. Schärfegrade: mild, leicht, mittel, Madras, Vindaloo und Phall.'],
        platos: [
          ['Vegan Meat (Soy Based)', 'Carne vegana (a base de soja)', 'Veganes Fleisch (auf Sojabasis)',
           'Choose sauce and spice level.',
           'Elige la salsa y el nivel de picante.',
           'Sauce und Schärfegrad wählen.',
           '16.95', ''],
          ['Tofu', 'Tofu', 'Tofu',
           'Choose sauce and spice level.',
           'Elige la salsa y el nivel de picante.',
           'Sauce und Schärfegrad wählen.',
           '15.95', ''],
          ['Traditional Soy (Processed Bean)', 'Soja tradicional (texturizada)', 'Traditionelle Soja (texturiert)',
           'Choose sauce and spice level.',
           'Elige la salsa y el nivel de picante.',
           'Sauce und Schärfegrad wählen.',
           '16.95', ''],
          ['Mixed Vegetables', 'Verduras variadas', 'Gemischtes Gemüse',
           'Choose sauce and spice level.',
           'Elige la salsa y el nivel de picante.',
           'Sauce und Schärfegrad wählen.',
           '12.95', ''],
          ['Mushrooms', 'Champiñones', 'Champignons',
           'Choose sauce and spice level.',
           'Elige la salsa y el nivel de picante.',
           'Sauce und Schärfegrad wählen.',
           '12.95', ''],
          ['Kathal (Raw Jackfruit)', 'Kathal (yaca verde)', 'Kathal (grüne Jackfrucht)',
           'Choose sauce and spice level.',
           'Elige la salsa y el nivel de picante.',
           'Sauce und Schärfegrad wählen.',
           '15.95', ''],
        ],
      },
      {
        categoria: 'Vegan - Vegetable Dishes',
        subtitulo: ['Vegetable Dishes', 'Platos de verdura', 'Gemüsegerichte'],
        icono: 'leaf',
        platos: [
          ['Bombay Aloo', 'Bombay Aloo', 'Bombay Aloo',
           'Vegan spiced potato dish.',
           'Plato vegano de patata especiada.',
           'Veganes Gericht mit gewürzten Kartoffeln.',
           '11.95', ''],
          ['Aloo Gobhi', 'Aloo Gobhi', 'Aloo Gobhi',
           'Vegan potato and cauliflower dish.',
           'Plato vegano de patata y coliflor.',
           'Veganes Gericht mit Kartoffel und Blumenkohl.',
           '11.95', ''],
          ['Aloo Mutter', 'Aloo Mutter', 'Aloo Mutter',
           'Vegan potato and peas dish.',
           'Plato vegano de patata y guisantes.',
           'Veganes Gericht mit Kartoffel und Erbsen.',
           '11.95', ''],
          ['Saag Aloo', 'Saag Aloo', 'Saag Aloo',
           'Vegan spinach and potato dish.',
           'Plato vegano de espinacas y patata.',
           'Veganes Gericht mit Spinat und Kartoffel.',
           '11.95', ''],
          ['Chana Masala', 'Chana Masala', 'Chana Masala',
           'Vegan chickpea curry.',
           'Curry vegano de garbanzos.',
           'Veganes Kichererbsencurry.',
           '12.95', ''],
          ['Aubergine Bharta', 'Bharta de berenjena', 'Auberginen-Bharta',
           'Vegan roasted aubergine curry.',
           'Curry vegano de berenjena asada.',
           'Veganes Curry mit gerösteter Aubergine.',
           '13.95', ''],
          ['Bhindi Masala', 'Bhindi Masala', 'Bhindi Masala',
           'Vegan okra dish.',
           'Plato vegano de okra.',
           'Veganes Okragericht.',
           '13.95', ''],
          ['Mutter Tofu', 'Mutter con tofu', 'Mutter mit Tofu',
           'Tofu and green peas.',
           'Tofu con guisantes.',
           'Tofu mit grünen Erbsen.',
           '15.95', ''],
          ['Palak Tofu', 'Palak con tofu', 'Palak mit Tofu',
           'Tofu with spinach.',
           'Tofu con espinacas.',
           'Tofu mit Spinat.',
           '15.95', ''],
          ['Navratan Korma', 'Navratan Korma', 'Navratan Korma',
           'Plant-based mixed vegetable korma.',
           'Korma de verduras de base vegetal.',
           'Gemüse-Korma auf pflanzlicher Basis.',
           '15.95', ''],
        ],
      },
      {
        categoria: 'Vegan - Indian Lentil Dishes',
        subtitulo: ['Indian Lentil Dishes', 'Lentejas indias', 'Indische Linsengerichte'],
        icono: 'lentils',
        platos: [
          ['Yellow Dal Tadka', 'Dal Tadka amarillo', 'Gelbes Dal Tadka',
           'Vegan yellow lentils with tadka.',
           'Lentejas amarillas veganas con tadka.',
           'Vegane gelbe Linsen mit Tadka.',
           '11.95', ''],
          ['Dal Makhani', 'Dal Makhani', 'Dal Makhani',
           'Plant-based black lentil dish.',
           'Lentejas negras de base vegetal.',
           'Schwarze Linsen auf pflanzlicher Basis.',
           '14.95', ''],
          ['Palak Dal', 'Palak Dal', 'Palak Dal',
           'Vegan lentils with spinach.',
           'Lentejas veganas con espinacas.',
           'Vegane Linsen mit Spinat.',
           '13.95', ''],
        ],
      },
      {
        categoria: 'Vegan - Special Biryani',
        subtitulo: ['Special Biryani', 'Biryani especial', 'Biryani Spezial'],
        icono: 'special',
        platos: [
          ['Vegan Meat', 'Carne vegana', 'Veganes Fleisch',
           'Biryani with soy-based vegan protein.',
           'Biryani con proteína vegana de soja.',
           'Biryani mit veganem Sojaprotein.',
           '19.95', ''],
          ['Tofu', 'Tofu', 'Tofu',
           'Biryani with tofu.',
           'Biryani con tofu.',
           'Biryani mit Tofu.',
           '17.95', ''],
          ['Soy', 'Soja', 'Soja',
           'Biryani with soy.',
           'Biryani con soja.',
           'Biryani mit Soja.',
           '18.95', ''],
          ['Mixed Vegetables', 'Verduras variadas', 'Gemischtes Gemüse',
           'Biryani with mixed vegetables.',
           'Biryani con verduras variadas.',
           'Biryani mit gemischtem Gemüse.',
           '16.95', ''],
          ['Mushrooms', 'Champiñones', 'Champignons',
           'Biryani with mushrooms.',
           'Biryani con champiñones.',
           'Biryani mit Champignons.',
           '16.95', ''],
          ['Kathal (Raw Jackfruit)', 'Kathal (yaca verde)', 'Kathal (grüne Jackfrucht)',
           'Biryani with raw jackfruit.',
           'Biryani con yaca verde.',
           'Biryani mit grüner Jackfrucht.',
           '18.95', ''],
        ],
      },
      {
        categoria: 'Vegan - Butter Masala Biryani',
        subtitulo: ['Butter Masala Biryani', 'Biryani Butter Masala', 'Butter-Masala-Biryani'],
        icono: 'rice',
        platos: [
          ['Tofu', 'Tofu', 'Tofu',
           'Plant-based butter-masala biryani with tofu.',
           'Biryani Butter Masala de base vegetal con tofu.',
           'Butter-Masala-Biryani auf pflanzlicher Basis mit Tofu.',
           '21.95', ''],
          ['Soy', 'Soja', 'Soja',
           'Plant-based butter-masala biryani with soy.',
           'Biryani Butter Masala de base vegetal con soja.',
           'Butter-Masala-Biryani auf pflanzlicher Basis mit Soja.',
           '21.95', ''],
          ['Vegan Meat', 'Carne vegana', 'Veganes Fleisch',
           'Plant-based butter-masala biryani with vegan meat.',
           'Biryani Butter Masala de base vegetal con carne vegana.',
           'Butter-Masala-Biryani auf pflanzlicher Basis mit veganem Fleisch.',
           '21.95', ''],
        ],
      },
      {
        categoria: 'Vegan - Rice & Fries',
        subtitulo: ['Rice & Fries', 'Arroces y patatas', 'Reis & Pommes'],
        icono: 'rice',
        nota: ['All rice dishes use Indian basmati rice.',
               'Todos los arroces se preparan con basmati indio.',
               'Alle Reisgerichte werden mit indischem Basmatireis zubereitet.'],
        platos: [
          ['Plain Boiled Rice', 'Arroz basmati hervido', 'Basmatireis',
           'Steamed basmati rice.',
           'Arroz basmati al vapor.',
           'Gedämpfter Basmatireis.',
           '3.50', ''],
          ['Pilao Rice', 'Arroz Pilao', 'Pilao-Reis',
           'Spiced basmati rice.',
           'Arroz basmati especiado.',
           'Gewürzter Basmatireis.',
           '4.00', ''],
          ['Cumin Rice', 'Arroz al comino', 'Reis mit Kreuzkümmel',
           'Cumin basmati rice.',
           'Arroz basmati al comino.',
           'Basmatireis mit Kreuzkümmel.',
           '4.50', ''],
          ['Garlic Rice', 'Arroz al ajo', 'Knoblauchreis',
           'Garlic basmati rice.',
           'Arroz basmati al ajo.',
           'Basmatireis mit Knoblauch.',
           '4.50', ''],
          ['Onion Rice', 'Arroz con cebolla', 'Reis mit Zwiebeln',
           'Onion basmati rice.',
           'Arroz basmati con cebolla.',
           'Basmatireis mit Zwiebeln.',
           '4.50', ''],
          ['Lemon Rice', 'Arroz al limón', 'Zitronenreis',
           'Lemon basmati rice.',
           'Arroz basmati al limón.',
           'Basmatireis mit Zitrone.',
           '4.50', ''],
          ['Mushroom Rice', 'Arroz con champiñones', 'Reis mit Champignons',
           'Mushroom basmati rice.',
           'Arroz basmati con champiñones.',
           'Basmatireis mit Champignons.',
           '4.50', ''],
          ['Mixed Vegetable Rice', 'Arroz con verduras', 'Reis mit Gemüse',
           'Vegetable basmati rice.',
           'Arroz basmati con verduras.',
           'Basmatireis mit Gemüse.',
           '4.50', ''],
          ['Coco Rice', 'Arroz con coco', 'Kokosreis',
           'Coconut basmati rice.',
           'Arroz basmati con coco.',
           'Basmatireis mit Kokos.',
           '4.50', ''],
          ['French Fries', 'Patatas fritas', 'Pommes frites',
           'Classic fries.',
           'Patatas fritas clásicas.',
           'Klassische Pommes frites.',
           '3.50', ''],
          ['Masala Fries', 'Patatas fritas Masala', 'Masala-Pommes',
           'Masala-seasoned fries.',
           'Patatas fritas con especias masala.',
           'Pommes frites mit Masala-Gewürzen.',
           '4.50', ''],
        ],
      },
      {
        categoria: 'Vegan - Sizzlers',
        subtitulo: ['Sizzlers', 'A la plancha', 'Vom heißen Eisen'],
        icono: 'flame',
        platos: [
          ['Tandoori Malai Broccoli', 'Brócoli Tandoori Malai', 'Tandoori Malai Brokkoli',
           'Plant-based creamy tandoori broccoli.',
           'Brócoli al tandoor con crema vegetal.',
           'Cremiger Tandoori-Brokkoli auf pflanzlicher Basis.',
           '14.95', ''],
          ['Tandoori Malai Soya', 'Soja Tandoori Malai', 'Tandoori Malai Soja',
           'Plant-based creamy tandoori soy.',
           'Soja al tandoor con crema vegetal.',
           'Cremige Tandoori-Soja auf pflanzlicher Basis.',
           '18.95', ''],
          ['Tofu Shashlik', 'Shashlik de tofu', 'Tofu-Shashlik',
           'Tofu shashlik served sizzling.',
           'Shashlik de tofu en plancha caliente.',
           'Tofu-Shashlik, heiß serviert.',
           '17.95', ''],
          ['Soy Shashlik', 'Shashlik de soja', 'Soja-Shashlik',
           'Soy shashlik served sizzling.',
           'Shashlik de soja en plancha caliente.',
           'Soja-Shashlik, heiß serviert.',
           '18.95', ''],
          ['Kathal Shashlik (Raw Jackfruit)', 'Shashlik de Kathal (yaca verde)', 'Kathal-Shashlik (grüne Jackfrucht)',
           'Jackfruit shashlik served sizzling.',
           'Shashlik de yaca en plancha caliente.',
           'Jackfrucht-Shashlik, heiß serviert.',
           '17.95', ''],
        ],
      },
      {
        categoria: 'Vegan - Flat Breads',
        subtitulo: ['Flat Breads', 'Panes planos', 'Fladenbrote'],
        icono: 'bread',
        platos: [
          ['Tandoori Roti', 'Roti Tandoori', 'Tandoori-Roti',
           'Vegan tandoori roti.',
           'Roti al tandoor vegano.',
           'Veganes Tandoori-Roti.',
           '4.25', ''],
          ['Garlic Tandoori Roti', 'Roti Tandoori de ajo', 'Tandoori-Roti mit Knoblauch',
           'Vegan garlic tandoori roti.',
           'Roti al tandoor vegano con ajo.',
           'Veganes Tandoori-Roti mit Knoblauch.',
           '4.75', ''],
          ['Garlic Chilli Tandoori Roti', 'Roti Tandoori de ajo y guindilla', 'Tandoori-Roti mit Knoblauch und Chili',
           'Vegan garlic-chilli tandoori roti.',
           'Roti al tandoor vegano con ajo y guindilla.',
           'Veganes Tandoori-Roti mit Knoblauch und Chili.',
           '5.50', ''],
          ['Cheese Tandoori Roti', 'Roti Tandoori de queso', 'Tandoori-Roti mit Käse',
           'Tandoori roti with vegan cheese.',
           'Roti al tandoor con queso vegano.',
           'Tandoori-Roti mit veganem Käse.',
           '6.00', ''],
          ['Cheese Garlic Tandoori Roti', 'Roti Tandoori de queso y ajo', 'Tandoori-Roti mit Käse und Knoblauch',
           'Tandoori roti with vegan cheese and garlic.',
           'Roti al tandoor con queso vegano y ajo.',
           'Tandoori-Roti mit veganem Käse und Knoblauch.',
           '6.25', ''],
          ['Cheese Garlic Chilli Tandoori Roti', 'Roti Tandoori de queso, ajo y guindilla', 'Tandoori-Roti mit Käse, Knoblauch und Chili',
           'Tandoori roti with vegan cheese, garlic and chilli.',
           'Roti al tandoor con queso vegano, ajo y guindilla.',
           'Tandoori-Roti mit veganem Käse, Knoblauch und Chili.',
           '6.50', ''],
          ['Peshwari Tandoori Roti', 'Roti Tandoori Peshwari', 'Peshwari-Tandoori-Roti',
           'Sweet-style vegan tandoori roti.',
           'Roti al tandoor vegano en versión dulce.',
           'Veganes Tandoori-Roti in süßer Variante.',
           '6.50', ''],
          ['Plain Chapati', 'Chapati natural', 'Chapati natur',
           'Vegan plain chapati.',
           'Chapati natural vegano.',
           'Veganes Chapati natur.',
           '3.25', ''],
          ['Vegan Butter Chapati', 'Chapati con mantequilla vegana', 'Chapati mit veganer Butter',
           'Chapati with vegan butter.',
           'Chapati con mantequilla vegana.',
           'Chapati mit veganer Butter.',
           '3.75', ''],
          ['Garlic Chapati', 'Chapati de ajo', 'Chapati mit Knoblauch',
           'Vegan garlic chapati.',
           'Chapati vegano al ajo.',
           'Veganes Chapati mit Knoblauch.',
           '3.95', ''],
          ['Aloo Paratha (Stuffed with Potatoes)', 'Aloo Paratha (relleno de patata)', 'Aloo Paratha (gefüllt mit Kartoffeln)',
           'Vegan paratha stuffed with potatoes.',
           'Paratha vegano relleno de patata.',
           'Veganes Paratha mit Kartoffelfüllung.',
           '5.50', ''],
        ],
      },
    ],
  },
];
